#!/usr/bin/env python3
"""
Massive occupation expansion v2: 1500 total with descriptions.
Generates programmatically using title components, avoiding manual listing.
"""
import json, random, itertools
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEAM_GEN = ROOT / 'system' / 'team-gen.json'

rnd = random.Random(42)

def r(a,b): return [a,b]

def occ(id_, label, archetype, rarity, tags, str_r, agi_r, end_r, int_r, lck_r, psy_r, skills, desc):
    return dict(id=id_, label=label, archetype=archetype, rarity=rarity, tags=tags, desc=desc,
                str=str_r, agi=agi_r, end=end_r, int=int_r, lck=lck_r, psy=psy_r, skills=skills)

# ── Load existing data ─────────────────────────────────────────
with open(TEAM_GEN, 'r', encoding='utf-8') as f:
    data = json.load(f)

existing_ids = {o['id'] for o in data['occupations']}
# Add desc to existing if missing
ARCH_DESC = {
    'working': lambda l: f"Worked as {l.lower()} before being pulled into God's Space.",
    'combat': lambda l: f"Trained as {l.lower()}. Experienced in high-stress, dangerous situations.",
    'medical': lambda l: f"Healthcare professional who worked as {l.lower()}. Trained in medical care.",
    'technical': lambda l: f"Technical specialist skilled as {l.lower()}. Adept with complex systems.",
    'academic': lambda l: f"Educated professional who worked as {l.lower()}. Deeply knowledgeable in their field.",
    'creative': lambda l: f"Creative force who worked as {l.lower()}. Expresses through their art.",
    'athletic': lambda l: f"Physically trained as {l.lower()}. Body is their primary instrument.",
    'investigative': lambda l: f"Investigator who worked as {l.lower()}. Trained to find answers.",
    'negative': lambda l: f"A person who was {l.lower()}. Severely disadvantaged in life.",
    'mystery': lambda l: f"Enigmatic figure. Worked as {l.lower()}. What they actually did is unclear."
}
for o in data['occupations']:
    if 'desc' not in o or not o['desc']:
        fn = ARCH_DESC.get(o.get('archetype',''), lambda l: f"Worked as {l.lower()}.")
        o['desc'] = fn(o['label'])

NEW = []  # fresh additions
CNT = {'common':0,'uncommon':0,'rare':0,'very_rare':0,'legendary':0}

def add(label, ar, ra, tags, st, ag, en, it, lk, ps, skills, desc):
    uid = f"occ-{len(data['occupations'])+len(NEW)+1:05d}"
    if uid in existing_ids:
        uid = f"occ-{len(data['occupations'])+len(NEW)+2:05d}"
    NEW.append(dict(id=uid, label=label, archetype=ar, rarity=ra, tags=tags, desc=desc,
                    str=st, agi=ag, end=en, int=it, lck=lk, psy=ps, skills=skills))
    CNT[ra] = CNT.get(ra,0)+1

# ════════════════════════════════════════════════════════════════
# GENERATE REGULAR OCCUPATIONS by title templates (~1000)
# ════════════════════════════════════════════════════════════════

# Write the giant script in parts to avoid truncation
output_parts = []
output_parts.append("Generating regular occupations...\n")

# Category-based generation
categories = {
    'medical': {
        'rarities': {'common':['Orderly','Hospital Porter','Medical Records Clerk','Phlebotomist','Home Health Aide'],
                     'uncommon':['Nurse','Dental Assistant','Optician','Physical Therapist','Midwife','Dietitian','Radiology Tech','Lab Technician','EMT',
                                 'Massage Therapist','Occupational Therapy Asst','Speech Therapy Asst','Medical Coder','Pharmacy Tech','Surgical Tech',
                                 'Paramedic','Veterinary Tech','Medical Office Manager'],
                     'rare':['General Practitioner','Veterinarian','Anesthesiologist','Dermatologist','Radiologist','Pathologist','Cardiologist',
                             'Neurologist','Pediatrician','Gynecologist','Urologist','Endocrinologist','Oncologist','Pulmonologist',
                             'Ophthalmologist','ENT Specialist','Orthopedic Surgeon','Plastic Surgeon','ER Physician','Clinical Psychologist',
                             'Hospital Administrator','Epidemiologist','Toxicologist','Pharmacist','Optometrist','Periodontist','Orthodontist',
                             'Oral Surgeon','Forensic Pathologist','Medical Examiner'],
                     'very_rare':['Chief of Surgery','Head of Neurology','Lead Transplant Surgeon','Chief Medical Officer','Psychiatric Director',
                                  'World-Renowned Specialist','Chief Epidemiologist'],
                     'legendary':['Nobel Prize-Winning Medical Researcher','Pioneering Transplant Surgeon','Legendary Neurosurgeon']},
        'arch': 'medical',
        'tags_base': ['medical'],
        'stat_base': {'str':[7,11],'agi':[9,13],'end':[9,13],'int':[14,18],'lck':[9,13],'psy':[11,15]},
        'stat_adj': {'common': {'int':[11,15]}, 'rare': {'int':[16,20]}, 'legendary': {'int':[18,22]}},
        'skills': {'basic': ['firstaid','patient_care','hygiene'], 'advanced': ['diagnosis','pharmacology','surgery','anatomy']}
    },
    'combat': {
        'rarities': {'common':['Security Guard','Bouncer','Parking Enforcement','Border Guard'],
                     'uncommon':['Police Officer','Corrections Officer','Soldier','Private Security','Riot Control Officer','Crowd Control Specialist',
                                 'K9 Handler','Marine','Infantryman','Combat Engineer'],
                     'rare':['SWAT Officer','Special Forces','Detective','Tactical Operator','Combat Medic','Sharpshooter','Military Intelligence',
                             'Bomb Squad Technician','Counter-Terrorism Operator','Force Recon','Ranger','Martial Arts Instructor'],
                     'very_rare':['Elite Sniper','Counter-Terrorism Commander','Black Ops Operator','Hostage Rescue Specialist','Spy',
                                  'Executive Protection Agent','PMC Director','Combat Instructor'],
                     'legendary':['Spec Ops Legend','Mercenary Warlord','Shadow Commander','Untraceable Operator']},
        'arch': 'combat',
        'tags_base': ['combat'],
        'stat_base': {'str':[12,16],'agi':[11,15],'end':[12,16],'int':[10,14],'lck':[9,13],'psy':[9,13]},
        'stat_adj': {'common': {'int':[8,12]}, 'legendary': {'str':[16,20],'agi':[15,19],'end':[16,20]}},
        'skills': ['firearms','melee','tactics','survival']
    },
    'working': {
        'rarities': {'common':['Cashier','Stock Clerk','Shelf Stocker','Janitor','Porter','Cleaner','Baggage Handler','Ticket Seller','Usher',
                               'Meter Reader','Mail Sorter','Flag Person','Crossing Guard','Library Page','Copy Shop Attendant','Delivery Person'],
                     'uncommon':['Postal Worker','Train Conductor','Flight Attendant','Property Manager','Store Manager','Restaurant Manager',
                                 'Hotel Manager','Office Manager','Hairdresser','Barber','Makeup Artist','Nail Technician','Esthetician',
                                 'Dry Cleaner','Tailor','Alterations Specialist','Cobbler','Upholsterer','Furniture Restorer',
                                 'Painter','Wallpaper Hanger','Carpet Layer','Flooring Installer','Roofer','Siding Installer',
                                 'Mover','Packer','Forklift Operator','Assembly Worker','Quality Inspector','Shipping Clerk','Receiving Clerk',
                                 'Tow Truck Driver','Ambulance Driver','Limo Driver','Chauffeur','Shuttle Driver','Transit Operator',
                                 'Maid','Butler','Concierge','Doorman','House Sitter'],
                     'rare':['Postmaster','Harbor Master','Tower Operator','Air Traffic Controller','Customs Officer','Immigration Officer',
                             'Funeral Director','Embalmer','Mortician','Bailiff','Court Clerk','Paralegal','Process Server'],
                     'very_rare':['Chief of Staff','Campaign Manager','Press Secretary','Public Relations Director','Head of Operations',
                                  'Chief Logistics Officer','Supply Chain Director','Master Butcher','Master Baker',
                                  'Executive House Manager','Estate Manager']},
        'arch': 'working',
        'tags_base': ['service'],
        'stat_base': {'str':[8,12],'agi':[8,12],'end':[9,13],'int':[9,13],'lck':[9,13],'psy':[8,12]},
        'stat_adj': {'rare': {'int':[13,17],'psy':[10,14]}, 'very_rare': {'int':[14,18],'lck':[12,16]}},
        'skills': ['customer_service','multi_tasking','organization']
    },
    'technical': {
        'rarities': {'common':['IT Support','Help Desk','Cable Installer','Satellite Installer','Copier Technician','Computer Repair',
                               'ATM Technician','Printer Repair','Phone Repair','Appliance Repair'],
                     'uncommon':['Electrician','Plumber','HVAC Tech','Appliance Installer','Locksmith','Auto Mechanic','Diesel Mechanic',
                                 'Small Engine Repair','Boat Mechanic','Bicycle Mechanic','Watch Repair','Jewelry Repair',
                                 'CNC Operator','Welder','Machinist','Toolmaker','Die Maker','Sheet Metal Worker','Line Installer',
                                 'Carpenter','Cabinet Maker','Woodworker','Tile Setter','Mason','Concrete Finisher','Glazier',
                                 'Elevator Mechanic','Escalator Mechanic','Vending Machine Tech','Wastewater Operator'],
                     'rare':['Network Engineer','Systems Admin','Database Admin','DevOps Engineer','Security Engineer','Cloud Architect',
                              'Software Architect','Machine Learning Engineer','Embedded Systems Engineer','Hardware Engineer',
                              'Robotics Engineer','Automation Engineer','Process Engineer','Structural Engineer','Electrical Engineer',
                              'Civil Engineer','Mechanical Engineer','Chemical Engineer','Biomedical Engineer','Audio Engineer',
                              'Sound Technician','Recording Engineer','Master Electrician','Master Plumber','General Contractor'],
                     'very_rare':['Principal Engineer','Chief Technology Officer','Systems Architect','Data Center Director',
                                  'R&D Director','Research Engineer','Patent Engineer','Forensic Engineer',
                                  'Chief Information Officer','Technology Director']},
        'arch': 'technical',
        'tags_base': ['technical'],
        'stat_base': {'str':[8,12],'agi':[9,13],'end':[9,13],'int':[13,17],'lck':[9,13],'psy':[8,12]},
        'stat_adj': {'rare': {'int':[15,19]}, 'legendary': {'int':[17,21]}},
        'skills': ['problem_solving','technical_knowledge','tool_use']
    },
    'academic': {
        'rarities': {'common':['Tutor','Substitute Teacher','Teaching Assistant','Daycare Worker','Preschool Teacher'],
                     'uncommon':['Teacher','School Counselor','Academic Advisor','ESL Instructor','Test Prep Coach',
                                 'Lab Assistant','Field Researcher','Surveyor','Cartographer'],
                     'rare':['Professor','Research Scientist','Postdoctoral Fellow','Principal','School Superintendent',
                             'Archaeologist','Geologist','Paleontologist','Astronomer','Meteorologist','Oceanographer',
                             'Seismologist','Botanist','Zoologist','Entomologist','Ornithologist','Mycologist',
                             'Anthropologist','Sociologist','Political Scientist','Economist','Historian','Philosopher',
                             'Linguist','Semiotician','Theologian','Ethicist'],
                     'very_rare':['Department Chair','Dean of Faculty','Research Director','Lead Scientist','Think Tank Fellow',
                                  'University President','Nobel Laureate Candidate','Leading Authority in Field']},
        'arch': 'academic',
        'tags_base': ['academic'],
        'stat_base': {'str':[6,10],'agi':[8,12],'end':[8,12],'int':[14,18],'lck':[9,13],'psy':[11,15]},
        'stat_adj': {'rare': {'int':[16,20]}, 'legendary': {'int':[18,22]}},
        'skills': ['research','teaching','writing','analysis']
    },
    'creative': {
        'rarities': {'common':['Photocopy Operator','Sign Painter','Billboard Painter','Greeting Card Writer','Calligrapher',
                               'Crafter','Candle Maker','Soap Maker','Potter','Weaver'],
                     'uncommon':['Photographer','Videographer','Editor','Copywriter','Proofreader','Ghostwriter','Technical Writer',
                                 'Screenwriter','Playwright','Poet','Novelist','Journalist','Columnist','Blogger',
                                 'Graphic Designer','Web Designer','UI Designer','Illustrator','Animator','Storyboard Artist',
                                 'Set Designer','Costume Designer','Lighting Designer','Makeup Artist','SFX Artist',
                                 'Dancer','Choreographer','Musician','Singer','Composer','Conductor',
                                 'Actor','Voice Actor','Stunt Double','Puppeteer','Mime','Juggler',
                                 'Art Teacher','Music Teacher','Dance Teacher','Acting Coach'],
                     'rare':['Art Director','Creative Director','Film Director','Music Producer','Record Label Owner',
                             'Gallery Curator','Published Author','Award-Winning Journalist','Principal Dancer',
                             'Orchestra Member','Lead Actor','Lead Singer','Songwriter','Choreographer (Professional)',
                             'Fashion Designer','Interior Designer','Landscape Designer','Architectural Designer',
                             'Art Restorer','Conservator','Master Printer','Bookbinder','Luthier'],
                     'very_rare':['Creative Director (Agency)','Artistic Director','Film Producer','Showrunner',
                                  'Executive Producer','Publisher','Editor-in-Chief','Master Artisan']},
        'arch': 'creative',
        'tags_base': ['creative'],
        'stat_base': {'str':[7,11],'agi':[10,14],'end':[8,12],'int':[12,16],'lck':[10,14],'psy':[12,16]},
        'stat_adj': {'rare': {'int':[14,18],'psy':[14,18]}, 'legendary': {'int':[16,20],'psy':[16,20]}},
        'skills': ['creativity','craft','self_expression']
    },
    'athletic': {
        'rarities': {'common':['Gym Cleaner','Pool Attendant','Locker Room Attendant','Ski Lift Operator','Trail Maintainer'],
                     'uncommon':['Personal Trainer','Group Fitness Instructor','Swim Instructor','Tennis Coach','Golf Caddy',
                                 'Sports Referee','Umpire','Linesperson','Scorekeeper','Timekeeper',
                                 'Zookeeper','Kennel Worker','Stable Hand','Dog Trainer','Horse Trainer',
                                 'Ski Instructor','Snowboard Instructor','Surf Instructor','Dive Instructor',
                                 'Rock Climbing Instructor','Yoga Instructor','Pilates Instructor','Martial Arts Instructor',
                                 'Cycling Instructor','Boxing Coach','Basketball Coach','Soccer Coach',
                                 'Outdoor Guide','Wilderness Guide','Fishing Guide','Hunting Guide'],
                     'rare':['Professional Athlete','Olympic Athlete','Sports Team Captain','Champion Fighter',
                             'Sports Agent','Sports Psychologist','Athletic Director','Head Coach',
                             'Wilderness Survival Instructor','Expedition Leader','Mountain Guide','Park Ranger'],
                     'very_rare':['Olympic Medalist','World Champion','Professional Team Captain','Elite Sports Agent']},
        'arch': 'athletic',
        'tags_base': ['athletic'],
        'stat_base': {'str':[11,15],'agi':[12,16],'end':[12,16],'int':[9,13],'lck':[10,14],'psy':[9,13]},
        'stat_adj': {'rare': {'str':[13,17],'agi':[14,18]}, 'legendary': {'str':[15,19],'agi':[16,20]}},
        'skills': ['physical_training','coordination','endurance']
    },
    'investigative': {
        'rarities': {'common':['Security Screener','Baggage Inspector','Customs Inspector','Loss Prevention Agent'],
                     'uncommon':['Private Investigator','Insurance Adjuster','Claims Investigator','Background Checker',
                                 'Skip Tracer','Forensic Accountant','Fraud Analyst','Compliance Officer'],
                     'rare':['Criminal Profiler','Forensic Scientist','Crime Scene Investigator','Ballistics Expert',
                             'Fingerprint Analyst','DNA Analyst','Toxicologist','Polygraph Examiner',
                             'Internal Affairs Investigator','Inspector General','Ombudsman'],
                     'very_rare':['Lead Investigator','Chief Inspector','Cold Case Specialist','Intelligence Analyst',
                                  'Counterintelligence Officer','Cyber Forensics Expert']},
        'arch': 'investigative',
        'tags_base': ['investigative'],
        'stat_base': {'str':[8,12],'agi':[10,14],'end':[9,13],'int':[13,17],'lck':[11,15],'psy':[11,15]},
        'stat_adj': {'rare': {'int':[15,19]}, 'legendary': {'int':[17,21],'psy':[14,18]}},
        'skills': ['observation','research','analysis','perception']
    },
}

for cat_name, cat in categories.items():
    arch = cat['arch']
    t_base = cat['tags_base']
    stat_base = cat['stat_base']
    stat_adj = cat.get('stat_adj', {})
    skills = cat.get('skills', [])
    for rarity, titles in cat['rarities'].items():
        adj = stat_adj.get(rarity, {})
        s = [stat_base['str'][0]+adj.get('str',[0,0])[0], stat_base['str'][1]+adj.get('str',[0,0])[0]]
        a = [stat_base['agi'][0]+adj.get('agi',[0,0])[0], stat_base['agi'][1]+adj.get('agi',[0,0])[0]]
        e = [stat_base['end'][0]+adj.get('end',[0,0])[0], stat_base['end'][1]+adj.get('end',[0,0])[0]]
        it = [stat_base['int'][0]+adj.get('int',[0,0])[0], stat_base['int'][1]+adj.get('int',[0,0])[0]]
        l = [stat_base['lck'][0]+adj.get('lck',[0,0])[0], stat_base['lck'][1]+adj.get('lck',[0,0])[0]]
        p = [stat_base['psy'][0]+adj.get('psy',[0,0])[0], stat_base['psy'][1]+adj.get('psy',[0,0])[0]]
        for title in titles:
            add(title, arch, rarity, t_base, s, a, e, it, l, p, skills,
                f"Worked as {title.lower()}. {cat.get('_desc','')}")

# ── Vaguer / broader titles ───────────────────────────────────
vague_jobs = {
    'common': ['Freelancer','Independent Contractor','Solo Practitioner','Temp Worker','Odd Job Worker',
               'Handyman','Tinkerer','Fixer','Dabbler','Hobbyist','Mentor','Life Coach','Busker'],
    'uncommon': ['Consultant','Specialist','Analyst','Coordinator','Facilitator','Mediator','Arbitrator',
                 'Contractor','Subcontractor','Franchise Owner','Distributor','Wholesaler','Broker',
                 'Agent','Representative','Liaison','Intermediary','Middleman','Connector'],
    'rare': ['Strategy Consultant','Management Consultant','Business Coach','Executive Coach',
             'Independent Researcher','Thought Leader','Subject Matter Expert'],
    'very_rare': ['High-Value Consultant','Crisis Manager','Turnaround Specialist','Industry Insider',
                  'Power Broker','Kingmaker'],
    'legendary': ['Shadow Advisor','The Power Behind the Throne','Legendary Strategist',
                  'The Untouchable','The Fixer of Last Resort']
}
for ra, titles in vague_jobs.items():
    for t in titles:
        add(t, 'working', ra, ['vague'], r(7,12), r(8,13), r(8,13), r(11,16), r(10,15), r(10,15),
            ['adaptability','networking','problem_solving'],
            f"Worked as {t.lower()}. Their exact role was somewhat undefined.")

# ── Criminal occupations ──────────────────────────────────────
criminal_jobs = {
    'uncommon': ['Pickpocket','Con Artist','Fence','Bootlegger','Burglar','Car Thief','Shoplifter',
                 'Street Hustler','Loan Shark','Numbers Runner','Stolen Goods Dealer'],
    'rare': ['Forger','Identity Thief','Hacker','Card Counter','Ponzi Schemer','Embezzler',
             'Insurance Fraudster','Tax Evader','Arms Trafficker','Drug Mule','Fence Master',
             'Safe Cracker','Art Thief','Jewel Thief','Cat Burglar','Getaway Driver','Enforcer',
             'Debt Collector (Illegal)','Protection Racket Operator','Bookmaker (Illegal)'],
    'very_rare': ['Counterfeiter','Money Launderer','Human Trafficker','Cocaine Trafficker',
                  'Heroin Trafficker','Weapons Trafficker','Cyber Criminal Mastermind',
                  'Heist Planner','Fence Kingpin','Illegal Arms Manufacturer'],
    'legendary': ['Crime Lord','Mafia Don','Cartel Leader','Yakuza Boss','Triad Leader',
                  'Russian Mafia Boss','Money Laundering King','Underground Banking Head',
                  'International Smuggler King','Untouchable Crime Boss']
}
for ra, titles in criminal_jobs.items():
    for t in titles:
        tags = ['criminal']
        desc = f"Criminal who worked as {t.lower()}. Operated outside the law."
        add(t, 'working', ra, tags, r(8,13), r(9,14), r(9,14), r(10,15), r(10,16), r(8,13),
            ['deception','street_smarts','survival_basic'], desc)

# ── Criminal combat occupations ────────────────────────────────
criminal_combat = {
    'uncommon': ['Street Fighter','Brawler','Enforcer','Debt Collector','Bouncer (Illegal)',
                 'Pit Fighter','Underground Boxer'],
    'rare': ['Muscle for Hire','Criminal Bodyguard','Getaway Driver (Combat)','Vault Cracker',
             'Hitman','Executioner','Drug Cartel Soldier'],
    'very_rare': ['Professional Assassin','Mafia Enforcer','Cartel Sicario','Torturer',
                  'Extermination Squad Leader'],
    'legendary': ['Legendary Hitman','Ghost Assassin','Untraceable Killer','Mafia Underboss']
}
for ra, titles in criminal_combat.items():
    for t in titles:
        add(t, 'combat', ra, ['criminal','combat'], r(11,16), r(11,16), r(11,16), r(9,14), r(9,14), r(8,12),
            ['melee','intimidation','street_smarts','survival','firearms'],
            f"Criminal enforcer type who worked as {t.lower()}.")

# ════════════════════════════════════════════════════════════════
# Add more normal jobs to hit counts per rarity
# ════════════════════════════════════════════════════════════════

# Common working-class additions
common_extra = [
    ('Dog Walker','working',['animal'],[8,12],[11,15],[10,14],[7,11],[9,13],[9,13],
     ['animal_handling','patience','route_planning'],"Walked dogs for busy pet owners."),
    ('Cat Sitter','working',['animal'],[7,11],[8,12],[8,12],[8,12],[9,13],[10,14],
     ['cat_knowledge','feeding','observation'],"Cared for cats while owners were away."),
    ('Plant Waterer','working',['service'],[7,11],[8,12],[8,12],[7,11],[8,12],[7,11],
     ['plant_care','watering_technique','observation'],"Watered plants in offices and homes."),
    ('Bicycle Messenger','working',['transport'],[9,13],[13,17],[12,16],[8,12],[11,15],[8,12],
     ['cycling','navigation','speed','package_handling','traffic_awareness'],"Delivered packages by bicycle in urban areas."),
    ('Pizza Delivery Driver','working',['transport','food'],[9,13],[9,13],[10,14],[8,12],[10,14],[9,13],
     ['driving','navigation','customer_service','time_management'],"Delivered pizzas to customers."),
    ('Newspaper Carrier','working',['transport'],[8,12],[10,14],[10,14],[7,11],[9,13],[7,11],
     ['early_rising','navigation','route_memory','speed'],"Delivered newspapers along a morning route."),
    ('Milkman','working',['transport'],[9,13],[9,13],[10,14],[8,12],[10,14],[8,12],
     ['early_rising','driving','route_memory','customer_service'],"Delivered milk and dairy products to homes."),
    ('Laundry Attendant','working',['service'],[9,13],[9,13],[10,14],[7,11],[8,12],[7,11],
     ['laundry_sorting','stain_treatment','machine_operation','fabric_care'],"Operated a laundromat or laundry service."),
    ('Locker Room Attendant','working',['service'],[8,12],[9,13],[9,13],[7,11],[8,12],[9,13],
     ['cleaning','customer_service','organization','towel_management'],"Maintained locker rooms at gyms or clubs."),
    ('Parking Lot Cashier','working',['service'],[7,11],[8,12],[8,12],[7,11],[8,12],[8,12],
     ['cash_handling','customer_service','patience','basic_math'],"Collected parking fees at a lot or garage."),
    ('Street Sweeper','working',['service'],[10,14],[9,13],[12,16],[6,10],[8,12],[6,10],
     ['sweeping','machine_operation','early_rising','route_following'],"Operated street cleaning equipment."),
    ('Bill Poster','working',['service'],[9,13],[10,14],[10,14],[7,11],[8,12],[7,11],
     ['poster_application','adhesive_knowledge','height_comfort','route_planning'],"Posted advertising bills and posters."),
    ('Sign Spinner','working',['service'],[8,12],[13,17],[10,14],[7,11],[10,14],[10,14],
     ['sign_spinning','showmanship','coordination','weather_tolerance'],"Spun advertising signs on street corners."),
    ('Costume Character Performer','working',['entertainment'],[9,13],[11,15],[11,15],[7,11],[9,13],[11,15],
     ['costume_performance','mime','heat_tolerance','children_entertainment','patience'],"Portrayed costumed characters at theme parks and events."),
    ('Arcade Technician','working',['technical'],[9,13],[10,14],[9,13],[11,15],[9,13],[8,12],
     ['electronics_repair','diagnostics','arcade_game_knowledge','tool_use'],"Repaired and maintained arcade machines."),
    ('Carnival Ride Operator','working',['entertainment'],[9,13],[9,13],[10,14],[8,12],[9,13],[9,13],
     ['ride_operation','safety_protocol','crowd_management','patience'],"Operated and supervised carnival rides."),
    ('Ferry Operator','working',['transport','maritime'],[10,14],[9,13],[11,15],[10,14],[10,14],[9,13],
     ['vessel_operation','navigation','safety_protocol','customer_service'],"Operated a passenger ferry service."),
    ('Crossing Guard','working',['safety'],[8,12],[10,14],[10,14],[7,11],[9,13],[9,13],
     ['traffic_control','child_safety','patience','alertness'],"Helped children cross streets safely near schools."),
    ('Lifeguard','working',['safety','athletic'],[10,14],[14,18],[13,17],[10,14],[11,15],[11,15],
     ['swimming','rescue','firstaid','observation','patience'],"Supervised swimming areas and performed rescues."),
    ('Valet Parker','working',['transport','service'],[9,13],[11,15],[10,14],[8,12],[11,15],[9,13],
     ['driving','customer_service','speed','parking_skill'],"Parked cars for hotel and restaurant guests."),
    ('Shoe Shiner','working',['service'],[7,11],[9,13],[9,13],[7,11],[9,13],[9,13],
     ['shoe_polishing','customer_service','attention_to_detail','patience'],"Polished shoes for customers at a stand or shop."),
    ('Porter','working',['service'],[10,14],[10,14],[11,15],[7,11],[9,13],[8,12],
     ['luggage_handling','customer_service','strength','hotel_knowledge'],"Carried luggage for hotel guests."),
    ('Elevator Attendant','working',['service'],[7,11],[8,12],[9,13],[6,10],[8,12],[8,12],
     ['elevator_operation','floor_memorization','customer_service','patience'],"Operated a manual elevator in an older building."),
    ('Coat Check Attendant','working',['service'],[7,11],[9,13],[9,13],[7,11],[8,12],[9,13],
     ['coat_management','ticket_system','organization','customer_service'],"Checked coats and bags at entertainment venues."),
    ('Ticket Taker','working',['service'],[7,11],[9,13],[9,13],[7,11],[8,12],[9,13],
     ['ticket_tearing','customer_service','crowd_direction','patience'],"Took tickets at theaters, venues, and attractions."),
    ('Program Seller','working',['service'],[7,11],[9,13],[9,13],[7,11],[9,13],[9,13],
     ['sales','program_knowledge','customer_service','patience'],"Sold programs and merchandise at events."),
    ('Concession Stand Worker','working',['service','food'],[9,13],[10,14],[10,14],[7,11],[8,12],[9,13],
     ['food_service','cash_handling','customer_service','speed'],"Worked at a concession stand selling food and drinks."),
    ('Candy Shop Worker','working',['service','food'],[8,12],[9,13],[9,13],[7,11],[9,13],[9,13],
     ['candy_knowledge','customer_service','sales','cleanliness'],"Worked in a candy or confectionery shop."),
    ('Deli Counter Worker','working',['service','food'],[10,14],[10,14],[10,14],[8,12],[9,13],[9,13],
     ['deli_meat_slicing','sandwich_making','customer_service','food_safety'],"Served customers at a deli counter."),
    ('Bakery Clerk','working',['service','food'],[9,13],[9,13],[10,14],[8,12],[9,13],[9,13],
     ['baking_knowledge','customer_service','cash_handling','display_setup'],"Worked the counter at a bakery."),
    ('Coffee Roaster','working',['food'],[10,14],[9,13],[10,14],[11,15],[10,14],[9,13],
     ['coffee_roasting','taste_discrimination','machine_operation','bean_knowledge'],"Roasted coffee beans for a coffee company."),
    ('Juice Bar Worker','working',['service','food'],[8,12],[10,14],[9,13],[7,11],[9,13],[9,13],
     ['juice_making','customer_service','cleanliness','ingredient_knowledge'],"Prepared fresh juices and smoothies for customers."),
    ('Smoothie Maker','working',['service','food'],[8,12],[10,14],[9,13],[7,11],[9,13],[9,13],
     ['blending','recipe_knowledge','customer_service','speed'],"Made smoothies at a health food or juice bar."),
    ('Sandwich Maker','working',['service','food'],[8,12],[10,14],[10,14],[7,11],[9,13],[9,13],
     ['sandwich_assembly','ingredient_knowledge','speed','customer_service'],"Made sandwiches to order at a deli or cafe."),
    ('Burger Flipper','working',['service','food'],[9,13],[10,14],[10,14],[6,10],[7,11],[8,12],
     ['grilling','speed','cleanliness','multi_tasking'],"Cooked burgers at a fast food restaurant."),
    ('Fry Cook','working',['service','food'],[9,13],[10,14],[11,15],[6,10],[7,11],[8,12],
     ['deep_frying','oil_temperature','speed','cleanliness','food_safety'],"Operated deep fryers at fast food restaurants."),
    ('Salad Prep','working',['service','food'],[8,12],[10,14],[9,13],[7,11],[8,12],[8,12],
     ['vegetable_chopping','knife_skill','recipe_following','speed'],"Prepared salads and ingredients in a restaurant kitchen."),
    ('Pantry Cook','working',['service','food'],[9,13],[9,13],[10,14],[8,12],[8,12],[8,12],
     ['ingredient_prep','storage_organization','inventory','food_safety'],"Managed the pantry station in a restaurant kitchen."),
    ('Pastry Chef','working',['food','creative'],[9,13],[12,16],[10,14],[12,16],[9,13],[10,14],
     ['pastry_making','baking','decoration','recipe_development','precision'],"Specialized in making pastries and desserts professionally."),
    ('Chocolatier','working',['food','creative'],[8,12],[12,16],[9,14],[12,16],[10,14],[10,14],
     ['chocolate_making','tempering','molding','creativity','precision'],"Created chocolate confections professionally."),
    ('Ice Cream Maker','working',['food'],[9,13],[9,13],[10,14],[9,13],[10,14],[8,12],
     ['ice_cream_making','flavor_development','freezing_technique','recipe_creation'],"Made ice cream in small batches."),
    ('Caterer','working',['food','service'],[10,14],[11,15],[11,15],[11,15],[10,14],[12,16],
     ['cooking_large_scale','menu_planning','logistics','client_management','food_safety'],"Provided prepared food for events and gatherings."),
    ('Personal Chef','working',['food','service'],[9,13],[10,14],[10,14],[12,16],[11,15],[12,16],
     ['cooking','menu_planning','dietary_knowledge','shopping','kitchen_management'],"Cooked private meals for individuals or families."),
    ('Private Tutor','academic',['academic'],[6,10],[8,12],[8,12],[14,18],[10,14],[13,17],
     ['teaching','subject_mastery','patience','communication','assessment'],"Provided one-on-one academic instruction to students."),
    ('Test Prep Coach','academic',['academic'],[6,10],[8,12],[8,12],[14,18],[11,15],[13,17],
     ['test_strategies','subject_knowledge','teaching','time_management','motivation'],"Helped students prepare for standardized tests."),
    ('Music Teacher','academic',['academic','creative'],[7,11],[12,16],[9,13],[12,16],[10,14],[13,17],
     ['instrument_proficiency','music_theory','teaching','patience','student_assessment'],"Taught music lessons (voice or instrument)."),
    ('Driving Instructor','working',['service'],[8,12],[10,14],[9,13],[10,14],[10,14],[11,15],
     ['driving','teaching','patience','safety_awareness','vehicle_knowledge'],"Taught people how to drive."),
    ('Flight Instructor','technical',['aviation','academic'],[9,13],[12,16],[10,14],[14,18],[12,16],[12,16],
     ['flying','teaching','patience','aviation_knowledge','safety_protocol'],"Taught people how to fly aircraft."),
    ('Scuba Instructor','athletic',['athletic','maritime'],[10,14],[13,17],[12,16],[11,15],[11,15],[11,15],
     ['diving','teaching','dive_physics','rescue','equipment_maintenance'],"Taught scuba diving certification courses."),
    ('Language Teacher','academic',['academic'],[6,10],[8,12],[8,12],[14,18],[10,14],[13,17],
     ['language_teaching','linguistics','patience','cultural_knowledge','curriculum_planning'],"Taught foreign languages to students."),
    ('Special Ed Teacher','academic',['academic','helping'],[8,12],[9,13],[10,14],[14,18],[10,14],[15,19],
     ['special_education','patience','behavior_management','curriculum_adaptation','empathy'],"Educated students with special needs."),
    ('Translator','academic',['academic'],[6,10],[8,12],[8,12],[15,19],[10,14],[12,16],
     ['translation','language_mastery','cultural_knowledge','research','attention_to_detail'],"Translated written materials between languages."),
    ('Interpreter','academic',['academic'],[7,11],[10,14],[9,13],[15,19],[11,15],[14,18],
     ['interpretation','language_mastery','quick_thinking','cultural_brokerage','discretion'],"Provided real-time spoken translation between languages."),
    ('Court Interpreter','academic',['academic','legal'],[7,11],[9,13],[9,13],[16,20],[11,15],[14,18],
     ['legal_terminology','interpretation','impartiality','memory','cultural_nuance'],"Interpreted for non-native speakers in court proceedings."),
    ('Medical Translator','academic',['academic','medical'],[6,10],[8,12],[9,13],[15,19],[10,14],[13,17],
     ['medical_terminology','translation','cultural_sensitivity','discretion','accuracy'],"Translated medical documents for healthcare settings."),
    ('Sign Language Interpreter','academic',['academic','helping'],[7,11],[12,16],[9,13],[13,17],[11,15],[14,18],
     ['sign_language','interpretation','facial_expression','cultural_awareness','patience'],"Interpreted spoken language into sign language for the deaf."),
    ('Braille Transcriber','academic',['academic','helping'],[6,10],[11,15],[9,13],[12,16],[9,13],[10,14],
     ['braille','transcription','attention_to_detail','patience','accuracy'],"Transcribed written materials into Braille."),
    ('Genealogist','academic',['academic'],[6,10],[8,12],[8,12],[14,18],[11,15],[11,15],
     ['genealogy','research','record_analysis','interviewing','attention_to_detail'],"Researched family histories for clients."),
    ('Numismatist','working',['business'],[6,10],[9,13],[8,12],[12,16],[13,17],[10,14],
     ['coin_appraisal','authentication','market_knowledge','cataloging','research'],"Specialized in coin and currency collecting and dealing."),
    ('Philatelist','working',['business'],[6,10],[9,13],[8,12],[12,16],[13,17],[10,14],
     ['stamp_appraisal','authentication','market_knowledge','cataloging','research'],"Specialized in stamp collecting and dealing."),
    ('Book Appraiser','working',['business','academic'],[6,10],[9,13],[8,12],[14,18],[12,16],[10,14],
     ['book_appraisal','literary_knowledge','condition_assessment','research','negotiation'],"Assessed the value of rare and antique books."),
    ('Art Appraiser','working',['business','art'],[6,10],[9,13],[8,12],[14,18],[13,17],[11,15],
     ['art_appraisal','art_history','authentication','market_knowledge','research'],"Assessed the value of artwork for insurance or sale."),
    ('Gemologist','technical',['technical','business'],[7,11],[12,16],[9,13],[14,18],[11,15],[9,13],
     ['gem_identification','grading','microscopy','market_knowledge','appraisal'],"Specialized in identifying and grading gemstones."),
    ('Auctioneer','working',['business'],[8,12],[9,13],[10,14],[12,16],[13,17],[14,18],
     ['auctioneering','rapid_speech','crowd_reading','valuation','salesmanship'],"Conducted live auctions of goods and property."),
    ('Property Appraiser','working',['business'],[8,12],[9,13],[9,13],[13,17],[11,15],[10,14],
     ['property_valuation','market_analysis','inspection','report_writing','legal_knowledge'],"Assessed the value of real estate properties."),
    ('Tax Assessor','working',['government'],[7,11],[8,12],[9,13],[14,18],[10,14],[10,14],
     ['tax_law','valuation','analysis','auditing','attention_to_detail'],"Assessed property values for tax purposes."),
    ('City Planner','technical',['government','technical'],[8,12],[9,13],[10,14],[15,19],[11,15],[12,16],
     ['urban_planning','zoning','public_consultation','mapping','regulation_knowledge'],"Planned land use and urban development for a municipality."),
    ('Urban Designer','creative',['creative','government'],[8,12],[10,14],[9,13],[14,18],[11,15],[12,16],
     ['urban_design','public_space_design','community_engagement','sketching','planning'],"Designed public spaces and urban environments."),
    ('Traffic Engineer','technical',['technical','government'],[9,13],[10,14],[10,14],[14,18],[10,14],[9,13],
     ['traffic_analysis','road_design','safety_engineering','data_analysis','signal_timing'],"Designed and optimized traffic systems."),
    ('Environmental Scientist','academic',['academic','science'],[8,12],[9,13],[9,13],[15,19],[10,14],[11,15],
     ['environmental_science','field_sampling','lab_analysis','report_writing','regulation_knowledge'],"Studied and analyzed the natural environment."),
    ('Conservation Officer','working',['government','outdoor'],[11,15],[11,15],[12,16],[12,16],[11,15],[11,15],
     ['wildlife_knowledge','enforcement','survival','navigation','public_education'],"Enforced environmental and wildlife protection laws."),
    ('Park Warden','working',['outdoor','government'],[11,15],[11,15],[13,17],[12,16],[11,15],[11,15],
     ['park_management','survival','public_safety','wildlife_knowledge','navigation'],"Managed and protected a national or state park."),
    ('Forest Ranger','working',['outdoor','government'],[11,15],[12,16],[13,17],[11,15],[10,14],[10,14],
     ['forest_management','wildfire_suppression','firstaid','navigation','public_education'],"Protected and managed forest lands."),
    ('Game Warden','working',['outdoor','law_enforcement'],[12,16],[12,16],[13,17],[12,16],[11,15],[11,15],
     ['wildlife_enforcement','tracking','survival','firearms','investigation'],"Enforced hunting and fishing regulations."),
    ('Fisheries Officer','working',['maritime','government'],[10,14],[10,14],[11,15],[13,17],[11,15],[10,14],
     ['fisheries_management','boat_operation','enforcement','data_collection','regulation_knowledge'],"Managed and protected fish stocks and habitats."),
    ('Coast Guard Crew','working',['maritime','military'],[11,15],[12,16],[13,17],[11,15],[10,14],[10,14],
     ['boat_operation','rescue','navigation','firstaid','firearms'],"Performed maritime safety, rescue, and law enforcement."),
    ('Marine Surveyor','technical',['technical','maritime'],[9,13],[10,14],[10,14],[14,18],[11,15],[9,13],
     ['vessel_inspection','naval_architecture','report_writing','regulation_knowledge','surveying'],"Inspected and surveyed ships for condition and compliance."),
    ('Aircraft Mechanic','technical',['technical','aviation'],[11,15],[11,15],[11,15],[13,17],[10,14],[9,13],
     ['aircraft_maintenance','diagnostics','engine_repair','safety_inspection','tool_use'],"Maintained and repaired aircraft."),
    ('Avionics Technician','technical',['technical','aviation'],[8,12],[11,15],[9,13],[14,18],[10,14],[9,13],
     ['avionics','electronics','diagnostics','navigation_systems','repair'],"Maintained aircraft electronic and navigation systems."),
    ('Airfield Operations','working',['aviation','government'],[9,13],[9,13],[10,14],[12,16],[10,14],[9,13],
     ['airfield_safety','communications','vehicle_operation','emergency_response','coordination'],"Managed airfield ground operations."),
    ('Ramp Agent','working',['aviation','service'],[10,14],[10,14],[11,15],[8,12],[9,13],[8,12],
     ['baggage_handling','ground_equipment','safety_protocol','teamwork','speed'],"Handled baggage and cargo on airport tarmac."),
    ('Skycap','working',['aviation','service'],[10,14],[10,14],[11,15],[7,11],[9,13],[9,13],
     ['luggage_handling','customer_service','airport_knowledge','speed'],"Assisted airline passengers with luggage at curbside."),
    ('Ticket Agent','working',['service','transport'],[7,11],[9,13],[9,13],[10,14],[10,14],[11,15],
     ['booking_systems','customer_service','multi_tasking','fare_knowledge','complaint_handling'],"Sold tickets and assisted travelers at a transportation terminal."),
    ('Gate Agent','working',['aviation','service'],[7,11],[9,13],[9,13],[10,14],[10,14],[12,16],
     ['boarding_procedures','customer_service','crisis_management','communication','scheduling'],"Managed passenger boarding at airport gates."),
    ('Customer Service Rep','working',['service'],[7,11],[9,13],[9,13],[10,14],[9,13],[11,15],
     ['customer_service','complaint_handling','phone_etiquette','problem_solving','product_knowledge'],"Handled customer inquiries and complaints."),
    ('Inside Sales Rep','working',['business','sales'],[7,11],[8,12],[9,13],[11,15],[11,15],[12,16],
     ['sales','negotiation','product_knowledge','customer_relations','pipeline_management'],"Sold products or services from an office setting."),
    ('Outside Sales Rep','working',['business','sales'],[9,13],[10,14],[10,14],[11,15],[12,16],[12,16],
     ['sales','negotiation','networking','client_management','travel_management'],"Sold products or services through in-person meetings."),
    ('Brand Ambassador','working',['business','sales'],[8,12],[10,14],[9,13],[11,15],[12,16],[13,17],
     ['brand_representation','product_knowledge','customer_engagement','event_staffing','enthusiasm'],"Represented a brand at events and promotions."),
    ('Merchandiser','working',['business'],[9,13],[10,14],[10,14],[9,13],[9,13],[8,12],
     ['visual_merchandising','inventory','shelf_arrangement','planogram_following','reporting'],"Arranged products in retail stores for optimal display."),
    ('Buyer (Retail)','working',['business'],[8,12],[9,13],[9,13],[13,17],[13,17],[12,16],
     ['negotiation','trend_spottin","market_analysis','vendor_management','budgeting'],"Selected and purchased merchandise for retail stores."),
    ('Fashion Buyer','working',['business','fashion'],[7,11],[9,13],[9,13],[13,17],[14,18],[12,16],
     ['fashion_trends','negotiation','vendor_relations','market_analysis','budgeting'],"Selected fashion merchandise for retail."),
    ('Category Manager','working',['business'],[8,12],[9,13],[9,13],[14,18],[12,16],[12,16],
     ['category_strategy','vendor_management','pricing','inventory_planning','data_analysis'],"Managed a product category at a large retailer."),
    ('Supply Chain Analyst','working',['business','technical'],[8,12],[9,13],[9,13],[14,18],[11,15],[9,13],
     ['supply_chain','data_analysis','optimization','logistics','forecasting'],"Analyzed and optimized supply chain operations."),
    ('Logistics Coordinator','working',['business','transport'],[9,13],[9,13],[10,14],[12,16],[11,15],[9,13],
     ['logistics','scheduling','carrier_management','tracking','problem_solving'],"Coordinated the transportation and delivery of goods."),
    ('Fleet Manager','working',['transport','business'],[10,14],[9,13],[11,15],[13,17],[11,15],[10,14],
     ['fleet_management','vehicle_maintenance','driver_management','route_optimization','budgeting'],"Managed a company's vehicle fleet."),
    ('Warehouse Manager','working',['business','transport'],[11,15],[9,13],[12,16],[12,16],[10,14],[9,13],
     ['warehouse_ops','inventory_management','team_leadership','safety_protocol','logistics'],"Managed warehouse operations and staff."),
    ('Operations Manager','working',['business'],[10,14],[9,13],[11,15],[14,18],[12,16],[12,16],
     ['operations','team_leadership','process_improvement','budgeting','crisis_management'],"Oversaw day-to-day operations of a business."),
    ('General Manager','working',['business'],[10,14],[9,13],[11,15],[14,18],[13,17],[14,18],
     ['general_management','staff_management','budgeting','strategy','customer_relations'],"Managed all aspects of a business location or division."),
    ('District Manager','working',['business'],[9,13],[9,13],[11,15],[14,18],[13,17],[14,18],
     ['multi_site_management','staff_development','budgeting','performance_analysis','regional_strategy'],"Managed multiple locations of a business across a district."),
    ('Regional Director','working',['business','elite'],[9,13],[10,14],[11,15],[15,19],[13,17],[15,19],
     ['regional_strategy','executive_leadership','budget_management','stakeholder_relations','crisis_management'],"Directed operations across an entire region."),
    ('Executive Assistant','working',['business'],[7,11],[10,14],[10,14],[13,17],[11,15],[13,17],
     ['calendar_management','communication','organization','discretion','multi_tasking'],"Provided high-level administrative support to executives."),
    ('Personal Assistant','working',['service'],[7,11],[10,14],[10,14],[11,15],[10,14],[13,17],
     ['scheduling','errand_running','organization','discretion','problem_solving'],"Handled personal tasks and schedules for individuals."),
    ('Virtual Assistant','working',['service','technical'],[6,10],[9,13],[8,12],[12,16],[10,14],[11,15],
     ['remote_administration','digital_organization','communication','multi_tasking','tech_proficiency'],"Provided administrative support remotely."),
    ('Office Administrator','working',['service'],[7,11],[9,13],[9,13],[12,16],[9,13],[11,15],
     ['office_management','organization','supply_ordering','record_keeping','staff_coordination'],"Handled administrative tasks for an office."),
    ('Data Entry Clerk','working',['service'],[6,10],[10,14],[9,13],[9,13],[8,12],[7,11],
     ['typing_speed','data_entry','accuracy','attention_to_detail','software_proficiency'],"Entered and maintained data in computer systems."),
    ('File Clerk','working',['service'],[6,10],[9,13],[9,13],[8,12],[8,12],[7,11],
     ['filing','organization','alphabetization','attention_to_detail','retrieval'],"Organized and maintained paper and digital filing systems."),
    ('Mail Clerk','working',['service'],[8,12],[9,13],[9,13],[7,11],[9,13],[7,11],
     ['mail_sorting','package_handling','route_management','organization','metering'],"Processed incoming and outgoing mail for an organization."),
    ('Dispatcher','working',['service','transport'],[8,12],[9,13],[10,14],[11,15],[10,14],[10,14],
     ['dispatching','scheduling','multi_tasking','communication','crisis_management'],"Coordinated the assignment of vehicles or personnel to jobs."),
    ('Emergency Dispatcher','working',['safety','emergency'],[9,13],[9,13],[10,14],[12,16],[10,14],[12,16],
     ['emergency_dispatch','calm_under_pressure','multi_tasking','map_reading','crisis_communication'],"Answered emergency calls and dispatched first responders."),
    ('911 Operator','working',['safety','emergency'],[8,12],[9,13],[10,14],[12,16],[10,14],[13,17],
     ['call_handling','crisis_deescalation','multi_tasking','map_reading','calm_under_pressure','protocol_following'],"Answered emergency calls and directed first responders."),
    ('Hotel Night Auditor','working',['hospitality'],[7,11],[9,13],[10,14],[11,15],[10,14],[9,13],
     ['night_audit','accounting','customer_service','front_desk_ops','reporting'],"Managed hotel front desk and accounting during night shifts."),
    ('Housekeeping Supervisor','working',['hospitality'],[9,13],[10,14],[11,15],[10,14],[9,13],[10,14],
     ['housekeeping_management','inspection','scheduling','training','inventory'],"Supervised housekeeping staff at a hotel."),
    ('Laundry Manager','working',['service'],[9,13],[9,13],[10,14],[10,14],[9,13],[9,13],
     ['laundry_operations','machinery','inventory','staff_management','quality_control'],"Managed commercial laundry operations."),
    ('Seamstress','working',['craft','skilled_trade'],[8,12],[13,17],[10,14],[9,13],[9,13],[9,13],
     ['sewing','alterations','pattern_making','fabric_knowledge','repair'],"Made and altered clothing professionally."),
    ('Cobbler','working',['craft','skilled_trade'],[9,13],[11,15],[10,14],[10,14],[9,13],[8,12],
     ['shoe_repair','leather_work','sole_attachment','heel_replacement','customer_service'],"Repaired and maintained shoes professionally."),
    ('Knitter','creative',['craft','creative'],[7,11],[12,16],[9,13],[9,13],[9,13],[10,14],
     ['knitting','pattern_reading','yarn_knowledge','garment_construction','creativity'],"Created knitted garments and items professionally."),
    ('Quilter','creative',['craft','creative'],[7,11],[11,15],[9,13],[10,14],[9,13],[10,14],
     ['quilting','pattern_design','fabric_selection','precision','creativity'],"Created quilts and quilted items professionally."),
    ('Embroidery Specialist','creative',['craft','creative'],[7,11],[13,17],[9,13],[9,13],[9,13],[10,14],
     ['embroidery','needlework','design','pattern_following','precision'],"Specialized in professional embroidery work."),
    ('Lace Maker','creative',['craft','creative'],[7,11],[14,18],[9,13],[10,14],[9,13],[9,13],
     ['lace_making','fine_motor_skills','patience','pattern_reading','design'],"Created lace fabric and trim professionally."),
    ('Basket Weaver','creative',['craft','creative'],[9,13],[11,15],[10,14],[9,13],[9,13],[9,13],
     ['basket_weaving','material_sourcing','pattern_design','patience','craftsmanship'],"Wove baskets from natural and synthetic materials."),
    ('Glassblower','technical',['craft','creative','technical'],[10,14],[13,17],[11,15],[12,16],[9,13],[10,14],
     ['glassblowing','heat_management','breath_control','form_creation','color_application'],"Created glass objects through blowing and shaping."),
    ('Stained Glass Artist','creative',['craft','creative'],[9,13],[12,16],[10,14],[12,16],[10,14],[11,15],
     ['stained_glass','glass_cutting','soldering','design','color_theory'],"Created stained glass windows and art pieces."),
    ('Blacksmith','technical',['craft','technical'],[14,18],[10,14],[14,18],[11,15],[9,13],[8,12],
     ['blacksmithing','metal_working','forge_operation','tool_making','repair'],"Forged metal items using heat and hammer."),
    ('Silversmith','technical',['craft','technical'],[10,14],[13,17],[10,14],[12,16],[10,14],[9,13],
     ['silversmithing','metal_working','precision_engraving','design','polishing'],"Created and repaired silver items."),
    ('Goldsmith','technical',['craft','technical','elite'],[9,13],[14,18],[10,14],[13,17],[11,15],[10,14],
     ['goldsmithing','precision_work','metal_alloying','gem_setting','design'],"Worked with gold and precious metals to create jewelry."),
    ('Leather Worker','technical',['craft','skilled_trade'],[10,14],[12,16],[10,14],[10,14],[9,13],[9,13],
     ['leather_working','cutting','stitching','tooling','design'],"Created and repaired leather goods."),
    ('Taxidermist','technical',['technical','craft'],[10,14],[12,16],[10,14],[13,17],[10,14],[11,15],
     ['taxidermy','anatomy','chemical_handling','sculpting','painting'],"Preserved and mounted animal specimens."),
    ('Model Maker','technical',['craft','technical'],[9,13],[13,17],[10,14],[12,16],[10,14],[10,14],
     ['model_making','scaling','painting','precision','tool_use'],"Created scale models for display or engineering."),
    ('Prototyper','technical',['technical'],[9,13],[12,16],[10,14],[14,18],[11,15],[9,13],
     ['prototyping','3d_printing','modeling','material_knowledge','problem_solving'],"Built prototypes of products for testing and development."),
    ('Theme Park Designer','creative',['creative','technical'],[9,13],[10,14],[10,14],[15,19],[12,16],[13,17],
     ['theme_design','ride_knowledge','storytelling','spatial_design','project_management'],"Designed theme park attractions and experiences."),
    ('Playground Designer','creative',['creative','technical'],[9,13],[10,14],[10,14],[13,17],[11,15],[11,15],
     ['playground_design','safety_compliance','spatial_planning','creativity','materials_knowledge'],"Designed playgrounds and recreational spaces."),
    ('Toy Designer','creative',['creative','technical'],[7,11],[10,14],[9,13],[13,17],[12,16],[11,15],
     ['toy_design','child_development','manufacturing_knowledge','safety_compliance','creativity'],"Designed toys for children."),
    ('Game Designer','creative',['creative','technical'],[7,11],[9,13],[9,13],[15,19],[12,16],[12,16],
     ['game_design','mechanics_design','level_design','player_psychology','system_thinking'],"Designed video games and interactive experiences."),
    ('Level Designer','creative',['creative','technical'],[7,11],[10,14],[9,13],[14,18],[11,15],[11,15],
     ['level_design','spatial_design','gameplay','3d_software','player_flow'],"Designed levels and environments for video games."),
    ('UI/UX Designer','technical',['creative','technical'],[6,10],[10,14],[8,12],[14,18],[11,15],[12,16],
     ['ux_design','wireframing','user_research','prototyping','visual_design'],"Designed user interfaces and experiences for digital products."),
    ('Product Manager','working',['business','technical'],[8,12],[9,13],[10,14],[15,19],[12,16],[13,17],
     ['product_strategy','user_research','roadmapping','cross_functional_leadership','data_analysis'],"Guided product development from concept to launch."),
    ('Project Manager','working',['business'],[8,12],[9,13],[10,14],[14,18],[11,15],[12,16],
     ['project_management','scheduling','budgeting','team_coordination','risk_management'],"Managed projects from initiation to completion."),
    ('Scrum Master','working',['technical','business'],[7,11],[9,13],[9,13],[13,17],[11,15],[13,17],
     ['agile_methodology','team_facilitation','conflict_resolution','coaching','removing_obstacles'],"Facilitated Agile development processes for teams."),
    ('Business Analyst','working',['business','technical'],[7,11],[9,13],[9,13],[14,18],[11,15],[11,15],
     ['business_analysis','requirements_gathering','process_modeling','data_analysis','stakeholder_management'],"Analyzed business needs and recommended solutions."),
    ('Quality Assurance Tester','technical',['technical'],[7,11],[10,14],[9,13],[12,16],[9,13],[9,13],
     ['testing','bug_reporting','attention_to_detail','test_case_writing','automation_basic'],"Tested software products for quality and bugs."),
    ('Technical Writer','creative',['technical','creative'],[6,10],[9,13],[8,12],[14,18],[10,14],[11,15],
     ['technical_writing','documentation','software_knowledge','editing','information_architecture'],"Wrote technical documentation and user guides."),
    ('Copy Editor','creative',['creative','media'],[6,10],[9,13],[8,12],[14,18],[10,14],[11,15],
     ['copy_editing','grammar','fact_checking','style_guides','proofreading'],"Edited written content for grammar, style, and accuracy."),
    ('Fact Checker','creative',['creative','media'],[6,10],[9,13],[8,12],[14,18],[11,15],[11,15],
     ['fact_checking','research','skepticism','source_verification','writing'],"Verified the accuracy of published information."),
    ('Acquisitions Editor','creative',['creative','business'],[6,10],[9,13],[9,13],[14,18],[12,16],[13,17],
     ['acquisitions','negotiation','market_awareness','author_relations','editorial_judgment'],"Selected and acquired manuscripts for publication."),
    ('Literary Agent','creative',['creative','business'],[7,11],[9,13],[9,13],[13,17],[13,17],[14,18],
     ['negotiation','manuscript_evaluation','publishing_knowledge','author_representation','networking'],"Represented writers in the publishing industry."),
    ('Talent Agent','working',['business','entertainment'],[8,12],[10,14],[9,13],[13,17],[14,18],[14,18],
     ['talent_representation','negotiation','networking','industry_knowledge','contract_review'],"Represented performers and creative professionals."),
    ('Booking Agent','working',['business','entertainment'],[8,12],[9,13],[9,13],[12,16],[13,17],[13,17],
     ['booking','negotiation','scheduling','artist_relations','venue_knowledge'],"Booked performances and appearances for artists."),
    ('Talent Scout','working',['business','entertainment'],[8,12],[10,14],[9,13],[13,17],[13,17],[12,16],
     ['talent_identification','networking','industry_knowledge','observation','assessment'],"Discovered new talent in entertainment or sports."),
    ('Casting Director','creative',['creative','entertainment'],[8,12],[10,14],[9,13],[13,17],[11,15],[14,18],
     ['casting','actor_evaluation','script_analysis','industry_knowledge','decision_making'],"Selected actors for film, TV, and theater productions."),
    ('Location Scout','creative',['creative','entertainment'],[9,13],[11,15],[11,15],[12,16],[13,17],[11,15],
     ['location_search','photography','creativity','logistics','negotiation'],"Found filming locations for movie and TV productions."),
    ('Prop Master','creative',['creative','entertainment'],[9,13],[11,15],[10,14],[12,16],[10,14],[10,14],
     ['prop_making','sourceing','organization','budget_management','creativity'],"Sourced and managed props for stage and screen."),
    ('Set Decorator','creative',['creative','entertainment'],[9,13],[11,15],[10,14],[12,16],[10,14],[12,16],
     ['set_decoration','interior_design','sourceing','period_knowledge','budgeting'],"Decorated film and TV sets with appropriate furnishings."),
    ('Costume Supervisor','creative',['creative','entertainment'],[8,12],[11,15],[10,14],[12,16],[10,14],[11,15],
     ['costume_management','wardrobe','sourceing','budgeting','team_coordination'],"Oversaw costumes for theater or film productions."),
    ('Makeup Department Head','creative',['creative','entertainment'],[8,12],[11,15],[10,14],[13,17],[10,14],[12,16],
     ['makeup_artistry','team_leadership','budgeting','creativity','sfx_makeup_basic'],"Led the makeup department for film or theater productions."),
    ('Hair Department Head','creative',['creative','entertainment'],[8,12],[11,15],[10,14],[11,15],[10,14],[12,16],
     ['hair_styling','department_management','period_hair','wig_work','team_coordination'],"Led the hair department for film or theater productions."),
    ('Sound Designer','creative',['creative','technical'],[7,11],[10,14],[9,13],[14,18],[11,15],[12,16],
     ['sound_design','audio_engineering','creativity','field_recording','post_production'],"Created soundscapes and audio for productions."),
    ('Composer','creative',['creative'],[6,10],[10,14],[9,13],[14,18],[12,16],[14,18],
     ['composition','music_theory','orchestration','creativity','studio_production'],"Created original music for various media."),
    ('Music Arranger','creative',['creative'],[7,11],[10,14],[9,13],[13,17],[11,15],[13,17],
     ['arrangement','orchestration','music_theory','transcription','creativity'],"Arranged music for different ensembles and contexts."),
    ('Orchestra Conductor','creative',['creative','elite'],[8,12],[12,16],[11,15],[15,19],[13,17],[16,20],
     ['conducting','repertoire_knowledge','leadership','interpretation','rehearsal_technique'],"Conducted orchestras in performance."),
    ('Choir Director','creative',['creative'],[7,11],[9,13],[10,14],[13,17],[11,15],[15,19],
     ['choral_conducting','voice_training','repertoire','rehearsal_planning','performance'],"Directed a choir or vocal ensemble."),
    ('Session Musician','creative',['creative'],[8,12],[13,17],[10,14],[12,16],[11,15],[12,16],
     ['instrument_mastery','sight_reading','versatility','studio_etiquette','improvisation'],"Played instruments for recording sessions and live performances."),
    ('Studio Engineer','technical',['technical','creative'],[8,12],[10,14],[9,13],[13,17],[10,14],[10,14],
     ['studio_recording','mixing','mastering','equipment_maintenance','production_software'],"Operated recording studio equipment and engineering sessions."),
    ('Mixing Engineer','technical',['technical','creative'],[7,11],[10,14],[9,13],[14,18],[10,14],[10,14],
     ['audio_mixing','critical_listening','processing','automation','collaboration'],"Mixed recorded tracks into final audio mixes."),
    ('Mastering Engineer','technical',['technical','creative'],[7,11],[10,14],[9,13],[14,18],[11,15],[10,14],
     ['mastering','critical_listening','loudness_optimization','format_preparation','quality_check'],"Prepared final mixes for distribution."),
    ('Touring Musician','creative',['creative'],[9,13],[12,16],[12,16],[10,14],[11,15],[12,16],
     ['instrument_mastery','travel_endurance','performance','improvisation','equipment_maintenance'],"Performed music as part of a touring act."),
    ('Roadie','working',['entertainment','technical'],[12,16],[10,14],[13,17],[9,13],[9,13],[8,12],
     ['equipment_handling','loading','setup_breakdown','cable_management','teamwork'],"Handled equipment setup and breakdown for touring shows."),
    ('Tour Manager','working',['entertainment','business'],[9,13],[10,14],[11,15],[13,17],[12,16],[13,17],
     ['tour_logistics','budgeting','artist_management','scheduling','crisis_management'],"Managed logistics and operations for touring acts."),
    ('Front of House Manager','working',['hospitality','service'],[9,13],[9,13],[10,14],[12,16],[11,15],[13,17],
     ['front_of_house','staff_management','customer_service','reservation_systems','complaint_handling'],"Managed the dining room and guest experience at a restaurant."),
    ('Sommelier','working',['hospitality','food'],[7,11],[9,13],[9,13],[13,17],[11,15],[13,17],
     ['wine_knowledge','wine_service','food_pairing','cellar_management','taste_discrimination'],"Managed wine service and selection at a restaurant."),
    ('Restaurant Owner','working',['business','hospitality'],[9,13],[9,13],[11,15],[13,17],[12,16],[13,17],
     ['restaurant_management','business_ops','staff_management','budgeting','customer_relations'],"Owned and operated a restaurant."),
    ('Food Critic','creative',['creative','food'],[6,10],[8,12],[8,12],[14,18],[13,17],[14,18],
     ['food_criticism','taste_discrimination','writing','restaurant_knowledge','palate_memory'],"Reviewed restaurants and wrote about food."),
    ('Food Stylist','creative',['creative','food'],[8,12],[12,16],[9,13],[11,15],[10,14],[11,15],
     ['food_styling','cooking','presentation','photography_knowledge','creativity'],"Styled food for photography and film."),
    ('Recipe Developer','creative',['creative','food'],[8,12],[10,14],[9,13],[12,16],[10,14],[10,14],
     ['recipe_development','cooking','measurement','nutrition_knowledge','testing'],"Created and tested recipes for publications."),
    ('Nutritionist','medical',['medical','food'],[7,11],[9,13],[9,13],[14,18],[10,14],[13,17],
     ['nutrition','dietary_planning','health_knowledge','counseling','meal_planning'],"Advised clients on diet and nutrition."),
    ('Personal Chef (Dietary)','working',['food','medical'],[9,13],[10,14],[10,14],[11,15],[10,14],[11,15],
     ['dietary_cooking','nutrition_knowledge','meal_prep','client_management','food_safety'],"Prepared specialized meals for clients with dietary needs."),
    ('Meal Prep Specialist','working',['food','service'],[9,13],[10,14],[10,14],[9,13],[10,14],[9,13],
     ['meal_prep','cooking_bulk','packaging','food_safety','delivery_logistics'],"Prepared and packaged ready-to-eat meals for clients."),
    ('Cannabis Grower','working',['agriculture','criminal'],[10,14],[9,13],[11,15],[10,14],[9,13],[8,12],
     ['cultivation','plant_care','harvesting','drying','strain_knowledge'],"Cultivated cannabis plants for medical or recreational use."),
    ('Master Distiller','technical',['craft','food'],[10,14],[10,14],[10,14],[13,17],[11,15],[10,14],
     ['distillation','fermentation','aging','blending','taste_discrimination'],"Produced distilled spirits professionally."),
    ('Master Brewer','technical',['craft','food'],[10,14],[10,14],[11,15],[13,17],[11,15],[10,14],
     ['brewing','fermentation','recipe_development','quality_control','equipment_maintenance'],"Brewed beer professionally."),
    ('Cider Maker','working',['craft','food'],[9,13],[9,13],[10,14],[11,15],[10,14],[9,13],
     ['cider_making','fermentation','apple_knowledge','pressing','blending'],"Made hard cider from apples."),
    ('Cheese Maker','working',['craft','food'],[10,14],[9,13],[10,14],[12,16],[10,14],[9,13],
     ['cheese_making','milk_knowledge','aging','curd_handling','affinage'],"Produced cheese professionally."),
    ('Butcher','working',['craft','food'],[13,17],[12,16],[12,16],[9,13],[9,13],[9,13],
     ['butchering','meat_cutting','knife_mastery','customer_service','inventory'],"Cut and prepared meat for sale."),
    ('Fish Monger','working',['craft','food','maritime'],[11,15],[10,14],[11,15],[9,13],[10,14],[8,12],
     ['fish_preparation','seafood_knowledge','customer_service','knife_skills','inventory'],"Sold fish and seafood at a market."),
    ('Ice Cutter','working',['craft'],[13,17],[9,13],[13,17],[7,11],[8,12],[7,11],
     ['ice_cutting','cold_tolerance','tool_use','strength','precision'],"Cut blocks of ice from frozen lakes for transport."),
    ('Lumberjack','working',['craft','outdoor'],[15,19],[10,14],[15,19],[8,12],[9,13],[7,11],
     ['tree_felling','chainsaw_use','log_rolling','timber_estimation','safety_protocol'],"Harvested trees for timber."),
    ('Arborist','working',['craft','outdoor'],[12,16],[13,17],[12,16],[11,15],[10,14],[9,13],
     ['tree_care','climbing','pruning','chainsaw_use','tree_diagnosis'],"Cared for and maintained trees professionally."),
    ('Forester','working',['outdoor','science'],[11,15],[11,15],[13,17],[13,17],[10,14],[9,13],
     ['forest_management','surveying','conservation','mapping','ecology'],"Managed forested lands for timber and conservation."),
    ('Shepherd','working',['agriculture','outdoor'],[10,14],[10,14],[12,16],[8,12],[12,16],[8,12],
     ['shepherding','animal_handling','herding','outdoor_survival','flock_health'],"Herded and cared for sheep."),
    ('Goat Herder','working',['agriculture','outdoor'],[10,14],[11,15],[12,16],[8,12],[11,15],[8,12],
     ['goat_handling','herding','mountain_walking','animal_health','milking'],"Herded and cared for goats."),
    ('Cowboy','working',['agriculture','outdoor'],[12,16],[12,16],[13,17],[9,13],[12,16],[9,13],
     ['horse_riding','ranching','animal_handling','roping','outdoor_survival'],"Worked on a cattle ranch, herding and managing livestock."),
    ('Rancher','working',['agriculture'],[12,16],[10,14],[13,17],[11,15],[11,15],[9,13],
     ['ranch_management','animal_husbandry','fencing','equipment_operation','business_management'],"Owned or managed a cattle or livestock ranch."),
    ('Apiarist (Beekeeper)','working',['agriculture'],[9,13],[10,14],[10,14],[11,15],[10,14],[9,13],
     ['beekeeping','hive_management','honey_extraction','bee_health','queen_rearing'],"Kept bees for honey production and pollination."),
    ('Poultry Farmer','working',['agriculture'],[10,14],[9,13],[11,15],[9,13],[10,14],[8,12],
     ['poultry_care','egg_collection','flock_health','coop_maintenance','processing'],"Raised chickens or other poultry for meat or eggs."),
    ('Pig Farmer','working',['agriculture'],[12,16],[9,13],[12,16],[9,13],[10,14],[8,12],
     ['pig_husbandry','farrowing','feeding','facility_cleaning','animal_health'],"Raised pigs for meat production."),
    ('Cattle Farmer','working',['agriculture'],[13,17],[10,14],[14,18],[10,14],[11,15],[9,13],
     ['cattle_husbandry','ranching','feeding','herd_health','equipment_operation'],"Raised cattle for beef or dairy production."),
    ('Dairy Farmer','working',['agriculture'],[12,16],[10,14],[13,17],[10,14],[11,15],[9,13],
     ['dairy_operation','milking','herd_health','equipment_maintenance','animal_husbandry'],"Operated a dairy farm producing milk."),
    ('Market Gardener','working',['agriculture'],[10,14],[10,14],[11,15],[10,14],[10,14],[9,13],
     ['vegetable_farming','crop_planning','irrigation','harvesting','customer_sales'],"Grew vegetables for sale at local markets."),
    ('Vineyard Worker','working',['agriculture'],[10,14],[10,14],[11,15],[9,13],[10,14],[8,12],
     ['vineyard_work','pruning','harvesting','trellising','irrigation'],"Cultivated grapevines in a vineyard."),
    ('Vintner','working',['agriculture','craft'],[10,14],[10,14],[11,15],[13,17],[12,16],[10,14],
     ['winemaking','fermentation','blending','barrel_aging','taste_discrimination'],"Made wine from grapes."),
    ('Mushroom Forager','working',['outdoor','food'],[9,13],[10,14],[10,14],[11,15],[11,15],[8,12],
     ['mushroom_identification','foraging','wild_food','mycology','safety_awareness'],"Foraged wild mushrooms for sale or consumption."),
    ('Truffle Hunter','working',['outdoor','food'],[9,13],[10,14],[11,15],[10,14],[12,16],[9,13],
     ['truffle_hunting','dog_handling','forest_knowledge','foraging','discretion'],"Sought and harvested truffles using trained animals."),
    ('Seaweed Harvester','working',['maritime'],[10,14],[10,14],[12,16],[8,12],[10,14],[7,11],
     ['seaweed_harvesting','marine_plant_knowledge','water_comfort','processing','boat_operation'],"Harvested seaweed from coastal waters."),
    ('Pearl Diver','working',['maritime','craft'],[10,14],[13,17],[12,16],[8,12],[12,16],[9,13],
     ['diving','pearl_identification','breath_holding','underwater_search','shell_opening'],"Dove for pearl-producing oysters."),
    ('Lobster Fisherman','working',['maritime'],[12,16],[11,15],[13,17],[9,13],[11,15],[8,12],
     ['lobster_trapping','boat_operation','navigation','weather_reading','heavy_lifting'],"Caught lobsters in traps."),
    ('Tuna Fisherman','working',['maritime'],[12,16],[11,15],[14,18],[9,13],[10,14],[8,12],
     ['tuna_fishing','longline_operation','boat_handling','navigation','fish_processing'],"Caught tuna commercially."),
    ('Whaler (Historical)','working',['maritime','historical'],[13,17],[11,15],[14,18],[10,14],[8,12],[9,13],
     ['whaling','harpooning','boat_operation','navigation','butchering'],"Hunted whales historically (pre-ban)."),
    ('Ice Road Trucker','working',['transport'],[12,16],[9,13],[14,18],[10,14],[10,14],[9,13],
     ['ice_driving','heavy_truck','survival','route_knowledge','vehicle_recovery'],"Drove trucks across frozen ice roads in remote regions."),
    ('Logging Truck Driver','working',['transport'],[12,16],[9,13],[13,17],[9,13],[9,13],[8,12],
     ['heavy_truck_driving','log_hauling','load_securing','route_planning','basic_mechanics'],"Transported logs from forests to mills."),
    ('Tanker Truck Driver','working',['transport'],[11,15],[9,13],[12,16],[10,14],[10,14],[8,12],
     ['tanker_driving','hazmat_handling','load_transfer','safety_protocol','route_planning'],"Drove tanker trucks carrying liquids or gases."),
    ('Hazmat Transporter','working',['transport','technical'],[11,15],[9,13],[12,16],[12,16],[10,14],[9,13],
     ['hazmat_handling','safety_protocol','emergency_response','documentation','vehicle_operation'],"Transported hazardous materials safely."),
    ('Armored Car Driver','working',['transport','security'],[11,15],[10,14],[12,16],[10,14],[11,15],[10,14],
     ['armored_driving','security_protocol','cash_handling','route_planning','situational_awareness'],"Drove armored vehicles transporting valuables."),
    ('Courier (Armed)','working',['transport','security'],[10,14],[11,15],[11,15],[10,14],[12,16],[10,14],
     ['armed_courier','route_planning','situational_awareness','defensive_driving','package_security'],"Transported valuable items with security measures."),
    ('Messenger (Foot)','working',['transport'],[8,12],[13,17],[12,16],[8,12],[11,15],[8,12],
     ['foot_messenger','navigation','speed','route_memory','reliability'],"Delivered messages on foot in urban areas."),
    ('Rickshaw Puller','working',['transport'],[13,17],[10,14],[14,18],[6,10],[8,12],[7,11],
     ['rickshaw_pulling','endurance','balance','navigation','customer_service'],"Pulled rickshaws to transport passengers."),
    ('Pedicab Driver','working',['transport','service'],[11,15],[11,15],[13,17],[8,12],[11,15],[9,13],
     ['pedicab_driving','navigation','customer_service','endurance','traffic_awareness'],"Operated a bicycle taxi for passengers."),
    ('Animal Cart Driver','working',['transport','agriculture'],[11,15],[9,13],[12,16],[7,11],[10,14],[7,11],
     ['animal_driving','cart_operation','animal_care','load_securing','navigation'],"Drove a cart pulled by horses, donkeys, or oxen."),
]
for entry in common_extra:
    label, arch, tags, s, a, e, it, lk, ps, skills, desc = entry
    ra = 'common'
    add(label, arch, ra, tags, s, a, e, it, lk, ps, skills, desc)

print(f"Common: {CNT['common']}, Uncommon: {CNT['uncommon']}, Rare: {CNT['rare']}, Very Rare: {CNT['very_rare']}, Legendary: {CNT['legendary']}")
print(f"Total new: {sum(CNT.values())}")

# ════════════════════════════════════════════════════════════════
# Combine and write
# ════════════════════════════════════════════════════════════════
data['occupations'].extend(NEW)
print(f"Total occupations in final file: {len(data['occupations'])}")

with open(TEAM_GEN, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Done!")
