#!/usr/bin/env python3
"""Second hobby expansion batch — target 1500 total."""
import json, sys
sys.stdout.reconfigure(encoding='utf-8')

PATH = 'system/team-gen.json'
with open(PATH, encoding='utf-8') as f:
    d = json.load(f)

RAW = [
# ── SPORTS VARIANTS ───────────────────────────────────────────
('Track Cycling',               'rare',     ['cycling','agility','endurance'],      'neutral'),
('BMX Racing',                  'rare',     ['cycling','agility'],                  'neutral'),
('BMX Freestyle',               'rare',     ['cycling','agility','acrobatics'],     'neutral'),
('Downhill Skateboarding',      'rare',     ['skateboarding','agility'],            'neutral'),
('Inline Speed Skating',        'rare',     ['skating','agility','endurance'],      'neutral'),
('Roller Derby',                'rare',     ['skating','agility','combat_training'],'neutral'),
('Figure Ice Skating',          'uncommon', ['skating','agility','balance'],        'neutral'),
('Speed Ice Skating',           'rare',     ['skating','agility','endurance'],      'neutral'),
('Curling',                     'uncommon', ['precision','tactics','teamwork'],     'neutral'),
('Ice Hockey (Amateur)',        'uncommon', ['skating','agility','teamwork'],       'neutral'),
('Floor Hockey',                'common',   ['agility','teamwork'],                 'neutral'),
('Bandy',                       'rare',     ['skating','agility'],                  'neutral'),
('Ultimate Frisbee',            'common',   ['agility','teamwork','endurance'],     'neutral'),
('Disc Golf',                   'common',   ['precision','patience'],               'neutral'),
('Rugby (Amateur)',             'uncommon', ['strength','agility','teamwork'],      'neutral'),
('Rugby League',                'uncommon', ['strength','endurance','teamwork'],    'neutral'),
('Touch Rugby',                 'common',   ['agility','teamwork'],                 'neutral'),
('American Football (Flag)',    'common',   ['agility','teamwork'],                 'neutral'),
('Australian Rules Football',   'uncommon', ['agility','endurance','teamwork'],     'neutral'),
('Gaelic Football',             'rare',     ['agility','endurance','teamwork'],     'neutral'),
('Hurling',                     'rare',     ['agility','coordination','endurance'], 'neutral'),
('Lacrosse',                    'uncommon', ['agility','teamwork','coordination'],  'neutral'),
('Field Hockey (Amateur)',      'uncommon', ['agility','teamwork'],                 'neutral'),
('Water Polo',                  'uncommon', ['swimming','endurance','teamwork'],    'neutral'),
('Underwater Hockey',           'rare',     ['swimming','endurance','teamwork'],    'neutral'),
('Synchronized Swimming',       'rare',     ['swimming','coordination'],            'neutral'),
('Canoe Sprint',                'rare',     ['rowing','endurance'],                 'neutral'),
('Flatwater Kayaking',          'uncommon', ['rowing','endurance'],                 'neutral'),
('Sea Kayaking',                'uncommon', ['rowing','navigation','endurance'],    'neutral'),
('Rowing (Sweep)',              'uncommon', ['rowing','endurance','teamwork'],      'neutral'),
('Sculling (Rowing)',           'rare',     ['rowing','endurance','coordination'],  'neutral'),
('Windsurfing',                 'rare',     ['sailing','balance','agility'],        'neutral'),
('Kitesurfing',                 'very_rare',['sailing','agility','endurance'],      'neutral'),
('Wakeboarding',                'uncommon', ['balance','agility'],                  'neutral'),
('Waterskiing',                 'uncommon', ['balance','agility'],                  'neutral'),
('Barefoot Waterskiing',        'very_rare',['balance','agility'],                  'neutral'),
('Surfing (Competition)',       'rare',     ['surfing','endurance'],                'neutral'),
('Bodyboarding',                'common',   ['swimming','agility'],                 'neutral'),
('Skimboarding',                'uncommon', ['balance','agility'],                  'neutral'),
('Knee Boarding',               'uncommon', ['balance','agility'],                  'neutral'),
('Snowboarding (Competition)',  'rare',     ['snowboarding','agility'],             'neutral'),
('Snowboarding (Backcountry)',  'very_rare',['snowboarding','survival','navigation'],'neutral'),
('Ski Jumping',                 'very_rare',['skiing','agility','endurance'],       'neutral'),
('Cross-Country Skiing',        'uncommon', ['skiing','endurance','navigation'],    'neutral'),
('Biathlon (Hobby)',            'very_rare',['skiing','marksmanship','endurance'],  'neutral'),
('Nordic Combined',             'very_rare',['skiing','endurance'],                 'neutral'),
('Telemark Skiing',             'rare',     ['skiing','agility'],                   'neutral'),
('Ski Touring',                 'rare',     ['skiing','survival','navigation'],     'neutral'),
('Snowshoeing',                 'common',   ['endurance','navigation'],             'neutral'),
('Fat Biking (Snow)',           'uncommon', ['cycling','endurance'],                'neutral'),
('Sled Dog Racing (Mushing)',   'very_rare',['animal_handling','endurance'],        'neutral'),
('Luge (Amateur)',              'very_rare',['agility','endurance'],                'neutral'),
('Bobsleigh (Amateur)',         'very_rare',['agility','endurance','teamwork'],     'neutral'),
('Polo',                        'very_rare',['equestrian','agility','tactics'],     'neutral'),
('Elephant Polo',               'legendary',['animal_handling','tactics'],          'neutral'),
('Canoe Polo',                  'rare',     ['boating','teamwork'],                 'neutral'),
('Underwater Rugby',            'rare',     ['swimming','strength','teamwork'],     'neutral'),
('Sepak Takraw',                'very_rare',['agility','acrobatics','coordination'],'neutral'),
('Kabaddi',                     'rare',     ['agility','endurance','combat_training'],'neutral'),
('Pesapallo (Finnish Baseball)','very_rare',['agility','teamwork'],                 'neutral'),
('Petanque',                    'common',   ['precision','patience'],               'neutral'),
('Bocce Ball',                  'common',   ['precision','patience'],               'neutral'),
('Quoits',                      'common',   ['precision'],                          'neutral'),
('Paddle Tennis',               'common',   ['agility','coordination'],             'neutral'),
('Platform Tennis',             'uncommon', ['agility','coordination','endurance'], 'neutral'),
('Squash',                      'uncommon', ['agility','endurance','coordination'], 'neutral'),
('Racquetball',                 'uncommon', ['agility','coordination'],             'neutral'),
('Pickleball',                  'common',   ['agility','coordination'],             'neutral'),
('Padel Tennis',                'common',   ['agility','teamwork','coordination'],  'neutral'),
('Soft Tennis',                 'common',   ['agility','coordination'],             'neutral'),
('Frontenis',                   'rare',     ['agility','coordination'],             'neutral'),
('Pelota Vasca',                'very_rare',['agility','strength'],                 'neutral'),
('Pétanque Competition',        'uncommon', ['precision','tactics'],                'neutral'),
('Golf Putting (Practice)',     'common',   ['precision','patience'],               'neutral'),
('Mini Golf',                   'common',   ['precision','patience'],               'neutral'),
('Footgolf',                    'uncommon', ['coordination','precision'],           'neutral'),
('Fistball',                    'rare',     ['agility','coordination','teamwork'],  'neutral'),
('Camogie',                     'rare',     ['agility','endurance'],                'neutral'),
('Netball',                     'common',   ['agility','teamwork','coordination'],  'neutral'),
('Korfball',                    'rare',     ['agility','teamwork'],                 'neutral'),
('Handball (Amateur)',          'common',   ['agility','endurance','teamwork'],     'neutral'),
('Beach Volleyball',            'common',   ['agility','teamwork','endurance'],     'neutral'),
('Snow Volleyball',             'uncommon', ['agility','teamwork','endurance'],     'neutral'),
('Seated Volleyball',           'uncommon', ['agility','teamwork'],                 'neutral'),
('Walking Football',            'common',   ['tactics','teamwork'],                 'neutral'),
('Blind Football',              'rare',     ['agility','teamwork','perception'],    'neutral'),
('Goalball',                    'rare',     ['teamwork','perception','agility'],    'neutral'),
('Boccia',                      'uncommon', ['precision','tactics'],                'neutral'),
('Wheelchair Rugby',            'rare',     ['agility','strength','teamwork'],      'neutral'),
# ── MARTIAL ARTS & COMBAT SPORTS ─────────────────────────────
('Savate (French Boxing)',      'rare',     ['martial_arts','agility','kicking'],   'neutral'),
('Lethwei (Burmese Boxing)',    'very_rare',['martial_arts','strength','endurance'],'neutral'),
('Sanda / Sanshou',             'rare',     ['martial_arts','agility'],             'neutral'),
('Baguazhang',                  'rare',     ['martial_arts','agility'],             'neutral'),
('Xingyiquan',                  'rare',     ['martial_arts','strength'],            'neutral'),
('Wing Chun',                   'uncommon', ['martial_arts','speed'],               'neutral'),
('Praying Mantis Kung Fu',      'rare',     ['martial_arts','agility'],             'neutral'),
('Drunken Fist',                'legendary',['martial_arts','agility','deception'], 'neutral'),
('White Crane Kung Fu',         'rare',     ['martial_arts','agility'],             'neutral'),
('Combat Sambo',                'rare',     ['martial_arts','strength'],            'neutral'),
('Systema',                     'very_rare',['martial_arts','agility'],             'neutral'),
('Krav Maga Fitness',           'common',   ['martial_arts','combat_training'],     'neutral'),
('Military Combatives (Hobby)', 'rare',     ['combat_training','strength'],         'neutral'),
('Dambe (West African Boxing)', 'very_rare',['martial_arts','strength'],            'neutral'),
('Laamb (Senegalese Wrestling)','very_rare',['martial_arts','strength'],            'neutral'),
('Schwingen (Swiss Wrestling)', 'very_rare',['martial_arts','strength'],            'neutral'),
('Glima (Norse Wrestling)',     'very_rare',['martial_arts','strength'],            'neutral'),
('Backhold Wrestling',          'very_rare',['strength','endurance'],               'neutral'),
('Sumo (Amateur)',              'uncommon', ['strength','martial_arts'],            'neutral'),
('Arm Wrestling',               'common',   ['strength'],                           'neutral'),
('Competitive Arm Wrestling',   'uncommon', ['strength','tactics'],                 'neutral'),
('Highland Games',              'rare',     ['strength','endurance'],               'neutral'),
('Stone of Strength (Kugelstossen)','very_rare',['strength'],                       'neutral'),
('Naginata',                    'very_rare',['martial_arts','agility','precision'], 'neutral'),
('Shinai Kendo (Casual)',       'uncommon', ['martial_arts','precision','agility'], 'neutral'),
('Silat',                       'rare',     ['martial_arts','agility'],             'neutral'),
('Capoeira Angola',             'rare',     ['martial_arts','dancing','agility'],   'neutral'),
('Hema (Historical Fencing)',   'rare',     ['fencing','history','strength'],       'neutral'),
('Longsword Fighting',          'rare',     ['melee','history','agility'],          'neutral'),
('Buhurt (Steel Fighting)',     'very_rare',['strength','endurance','combat_training'],'neutral'),
('Mounted Archery',             'very_rare',['archery','equestrian'],               'neutral'),
('Combat Archery',              'rare',     ['archery','agility'],                  'neutral'),
('Blowgun Sport',               'rare',     ['precision','breath_control'],         'neutral'),
('Sling Throwing',              'rare',     ['precision','agility'],                'neutral'),
# ── FITNESS & HEALTH ─────────────────────────────────────────
('Kettlebell Training',         'common',   ['strength','endurance'],               'neutral'),
('Functional Fitness (General)','common',   ['strength','endurance'],               'neutral'),
('CrossFit',                    'common',   ['strength','endurance','agility'],     'neutral'),
('Olympic Weightlifting',       'uncommon', ['strength','precision'],               'neutral'),
('Powerlifting',                'uncommon', ['strength','endurance'],               'neutral'),
('Strongman Training',          'rare',     ['strength','endurance'],               'neutral'),
('Calisthenics (Advanced)',     'uncommon', ['strength','agility'],                 'neutral'),
('Street Workout',              'uncommon', ['strength','agility'],                 'neutral'),
('TRX Suspension Training',    'common',   ['strength','balance'],                 'neutral'),
('Barre Fitness',               'common',   ['balance','strength','agility'],       'neutral'),
('Aqua Jogging',                'common',   ['endurance'],                          'neutral'),
('Nordic Walking',              'common',   ['endurance','navigation'],             'neutral'),
('Racewalking',                 'uncommon', ['endurance','coordination'],           'neutral'),
('Stair Climbing (Sport)',      'uncommon', ['endurance','strength'],               'neutral'),
('Indoor Climbing (General)',   'common',   ['climbing','strength','agility'],      'neutral'),
('Bouldering (Competition)',    'rare',     ['climbing','strength','agility'],      'neutral'),
('Grip Strength Training',      'uncommon', ['strength'],                           'neutral'),
('Obstacle Course Racing (OCR)','uncommon', ['strength','endurance','agility'],     'neutral'),
('Ninja Warrior Training',      'uncommon', ['agility','strength','endurance'],     'neutral'),
('Footbag / Hacky Sack',        'common',   ['coordination','agility'],             'neutral'),
('Slalom Skiing',               'rare',     ['skiing','agility','precision'],       'neutral'),
('Freestyle Skiing (Moguls)',   'very_rare',['skiing','agility'],                   'neutral'),
('Aerials Skiing',              'very_rare',['skiing','acrobatics'],                'neutral'),
('Ski Ballet',                  'very_rare',['skiing','dancing','agility'],         'neutral'),
('Blind Long Jump',             'rare',     ['agility','navigation'],               'neutral'),
# ── ESOTERIC / NICHE SPORTS ──────────────────────────────────
('Cheese Rolling',              'legendary',['agility','endurance','speed'],        'neutral'),
('Bog Snorkelling',             'legendary',['swimming','endurance'],               'neutral'),
('Wife Carrying (Competition)', 'legendary',['strength','agility','teamwork'],      'neutral'),
('Extreme Ironing',             'legendary',['agility','creativity'],               'neutral'),
('Underwater Pumpkin Carving',  'legendary',['diving','creativity'],                'neutral'),
('Toe Wrestling',               'legendary',['strength','agility'],                 'neutral'),
('Air Guitar Competition',      'very_rare',['music','humor','performance'],        'neutral'),
('Ferret Legging',              'legendary',['endurance','patience'],               'neutral'),
('Shin Kicking',                'legendary',['strength','endurance'],               'neutral'),
('Eukonkanto (Wife Carrying)',  'legendary',['strength','endurance'],               'neutral'),
# ── MUSIC GENRES & SUBCULTURES ───────────────────────────────
('Classical Music Appreciation','common',   ['music','knowledge'],                  'neutral'),
('Jazz Listening',              'common',   ['music','knowledge'],                  'neutral'),
('Metal Music (Heavy Listener)','common',   ['music','knowledge'],                  'neutral'),
('Metal Guitar (Extreme)',      'rare',     ['music','coordination'],               'neutral'),
('Bass-Heavy Music (DJ)',       'uncommon', ['music','rhythm'],                     'neutral'),
('Bluegrass Music',             'uncommon', ['music','knowledge'],                  'neutral'),
('Country Music (Playing)',     'common',   ['music','storytelling'],               'neutral'),
('Gospel Singing',              'uncommon', ['singing','social'],                   'good'),
('World Music Study',           'uncommon', ['music','knowledge','culture'],        'neutral'),
('Electronic Music Production', 'uncommon', ['music','programming'],                'neutral'),
('Ambient Music Composition',   'rare',     ['music','creativity'],                 'neutral'),
('Field Recording',             'rare',     ['observation','audio_engineering'],    'neutral'),
('Sound Design',                'rare',     ['creativity','audio_engineering'],     'neutral'),
('Choral Arrangement',          'rare',     ['music','mathematics'],                'neutral'),
('Music Festival Organising',   'rare',     ['leadership','organization','music'],  'neutral'),
('Band Management',             'very_rare',['music','leadership','business'],      'neutral'),
('Vinyl DJing (Turntablist)',   'uncommon', ['music','coordination'],               'neutral'),
('Live Looping Music',          'rare',     ['music','coordination','creativity'],  'neutral'),
# ── FOOD & DRINK SPECIFICS ───────────────────────────────────
('Competitive Barbecue',        'rare',     ['cooking','knowledge'],                'neutral'),
('Hot Sauce Making',            'uncommon', ['cooking','chemistry'],                'neutral'),
('Vinegar Making',              'rare',     ['cooking','chemistry','patience'],     'neutral'),
('Shrub Making (Drinking)',     'rare',     ['cooking','chemistry'],                'neutral'),
('Honey Wine (Mead) Making',   'uncommon', ['brewing','chemistry'],                'neutral'),
('Elderflower Cordial Making',  'uncommon', ['foraging','cooking'],                 'neutral'),
('Infused Spirits',             'uncommon', ['brewing','chemistry'],                'neutral'),
('Kvass Brewing',               'rare',     ['brewing','chemistry'],                'neutral'),
('Tepache Making',              'rare',     ['brewing','chemistry'],                'neutral'),
('Ginger Beer Brewing',         'uncommon', ['brewing','chemistry'],                'neutral'),
('Mushroom Chips / Jerky',      'uncommon', ['cooking','foraging'],                 'neutral'),
('Seaweed Cooking',             'uncommon', ['cooking','foraging'],                 'neutral'),
('Insect Cooking',              'very_rare',['cooking','knowledge'],                'neutral'),
('Fermented Fish (Hobbyist)',   'very_rare',['cooking','patience','chemistry'],     'neutral'),
('Raw Milk Cheesemaking',       'rare',     ['cooking','chemistry','patience'],     'neutral'),
('Yeast Propagation',           'rare',     ['brewing','chemistry'],                'neutral'),
('Truffle Hunting (Hobby)',     'very_rare',['foraging','animal_handling'],         'neutral'),
('Foie Gras Preparation',       'very_rare',['cooking','animal_handling'],          'neutral'),
('Competitive Baking',          'rare',     ['cooking','precision','endurance'],    'neutral'),
('Food Fermentation Lab',       'rare',     ['cooking','chemistry','biology'],      'neutral'),
('Soda Making (Carbonation)',   'uncommon', ['cooking','chemistry'],                'neutral'),
('Kombucha SCOBY Sharing',     'common',   ['brewing','social'],                   'neutral'),
('Coffee Cupping (Ritual)',     'uncommon', ['taste_discrimination','knowledge'],   'neutral'),
('Tea Blending',                'uncommon', ['chemistry','taste_discrimination'],   'neutral'),
# ── ART HISTORY & APPRECIATION ───────────────────────────────
('Art Gallery Visiting',        'common',   ['knowledge','observation'],            'neutral'),
('Art History Study',           'uncommon', ['knowledge','history'],                'neutral'),
('Museum Volunteering',         'uncommon', ['social','knowledge'],                 'good'),
('Art Auction Attending',       'rare',     ['knowledge','negotiation'],            'neutral'),
('Street Art Appreciation',     'common',   ['knowledge','observation'],            'neutral'),
('Classical Architecture Study','uncommon', ['knowledge','history'],                'neutral'),
# ── PERFORMANCE ARTS ─────────────────────────────────────────
('Monologue Practice',          'uncommon', ['acting','memory'],                    'neutral'),
('Shakespearean Acting',        'rare',     ['acting','knowledge'],                 'neutral'),
('Clowning',                    'uncommon', ['acting','social'],                    'neutral'),
('Theatrical Makeup',           'uncommon', ['creativity','precision'],             'neutral'),
('Costume Design',              'uncommon', ['sewing','creativity'],                'neutral'),
('Stage Management (Amateur)',  'rare',     ['leadership','organization'],          'neutral'),
('Playwriting Workshop',        'uncommon', ['writing','social'],                   'neutral'),
('Tabletop Roleplaying (Solo)', 'common',   ['creativity','writing'],               'neutral'),
('Interactive Theatre',         'rare',     ['acting','social'],                    'neutral'),
('Murder Mystery Hosting',      'uncommon', ['acting','social','organizing'],       'neutral'),
# ── CULTURAL & HERITAGE ──────────────────────────────────────
('Tea Ceremony (Japanese)',     'rare',     ['patience','culture','precision'],     'neutral'),
('Tea Ceremony (Chinese Gongfu)','rare',    ['patience','culture'],                 'neutral'),
('Ikebana (Advanced)',          'very_rare',['botany','creativity','patience'],     'neutral'),
('Calligraphy (Kana)',          'very_rare',['writing','patience','precision'],     'neutral'),
('Korean Pottery (Hobby)',      'rare',     ['sculpting','patience'],               'neutral'),
('Rangoli Making (Indian)',     'uncommon', ['creativity','precision'],             'neutral'),
('Henna / Mehndi Design',       'uncommon', ['precision','creativity'],             'neutral'),
('Batik (Indonesian)',          'rare',     ['crafting','patience'],                'neutral'),
('Wayang (Shadow Puppet)',      'very_rare',['acting','crafting','storytelling'],   'neutral'),
('Gamelan Playing',             'very_rare',['music','coordination','culture'],     'neutral'),
('Taiko Drumming',              'rare',     ['music','endurance'],                  'neutral'),
('Sitar Playing (Hobby)',       'rare',     ['music','patience'],                   'neutral'),
('Tabla Playing (Hobby)',       'rare',     ['music','rhythm'],                     'neutral'),
('Throat Singing',              'legendary',['music','breath_control'],             'neutral'),
('Overtone Singing',            'very_rare',['music','breath_control'],             'neutral'),
('Yodel Singing',               'very_rare',['singing','breath_control'],           'neutral'),
('Native Drum Circle',          'uncommon', ['music','rhythm','social'],            'neutral'),
('Aboriginal Dot Painting',     'very_rare',['painting','culture'],                 'neutral'),
('Kente Weaving',               'very_rare',['weaving','culture'],                  'neutral'),
('Adinkra Cloth Printing',      'very_rare',['printing','culture'],                 'neutral'),
('Madhubani Painting',          'very_rare',['painting','culture'],                 'neutral'),
('Polish Wycinanki Papercuts',  'very_rare',['paper_folding','precision','culture'],'neutral'),
('Mexican Alebrijes Sculpting', 'very_rare',['sculpting','creativity'],             'neutral'),
('Navajo Weaving',              'very_rare',['weaving','culture'],                  'neutral'),
('Quillwork (Native)',          'legendary',['precision','patience','culture'],     'neutral'),
('Haiku Writing',               'uncommon', ['writing','nature'],                   'neutral'),
('Tanka Poetry',                'rare',     ['writing','culture'],                  'neutral'),
('Ghazal Poetry',               'rare',     ['writing','culture'],                  'neutral'),
('Villanelle Writing',          'rare',     ['writing','creativity'],               'neutral'),
('Sonnet Writing',              'rare',     ['writing','creativity'],               'neutral'),
('Flash Fiction',               'uncommon', ['writing','creativity'],               'neutral'),
('Micro Fiction',               'uncommon', ['writing','creativity'],               'neutral'),
('Wuxia Fan Fiction',           'uncommon', ['writing','knowledge'],                'neutral'),
# ── NATURE SPORTS & ECO ─────────────────────────────────────
('Reef Conservation Diving',    'rare',     ['diving','biology','endurance'],       'good'),
('Seabird Monitoring (Volunteer)','uncommon',['observation','biology'],             'good'),
('Bat Watching (Chiropterology)','uncommon',['observation','biology'],              'neutral'),
('Owl Pellet Analysis',         'uncommon', ['biology','observation'],              'neutral'),
('Nocturnal Nature Walk',       'uncommon', ['observation','survival'],             'neutral'),
('Tide Calendar Study',         'uncommon', ['navigation','observation'],           'neutral'),
('Cloud Spotting',              'common',   ['observation','meteorology'],          'neutral'),
('Aurora Hunting',              'rare',     ['observation','navigation'],           'neutral'),
('Volcano Tourism',             'very_rare',['observation','endurance','survival'], 'neutral'),
('Earthquake Zone Hiking',      'very_rare',['survival','navigation'],              'neutral'),
('Extreme Weather Chasing',     'very_rare',['meteorology','driving'],              'neutral'),
('Ice Cave Exploration',        'very_rare',['survival','climbing','navigation'],   'neutral'),
('Lava Tube Hiking',            'rare',     ['navigation','geology'],               'neutral'),
('Thermal Pool Bathing',        'common',   ['endurance'],                          'neutral'),
('Wild Swimming in Lakes',      'common',   ['swimming','endurance'],               'neutral'),
('Peat Bog Study',              'rare',     ['biology','observation'],              'neutral'),
# ── SCIENCE & TECH EXTRAS ────────────────────────────────────
('Algorithm Visualization',     'rare',     ['programming','mathematics'],          'neutral'),
('Generative Art (Code)',       'rare',     ['programming','creativity'],           'neutral'),
('Data Sonification',           'very_rare',['programming','music'],                'neutral'),
('Amateur Seismology',          'very_rare',['physics','observation'],              'neutral'),
('Cosmic Ray Detection (DIY)', 'legendary',['physics','electronics'],              'neutral'),
('SETI@home (Hobby)',           'uncommon', ['astronomy','computing'],              'neutral'),
('Protein Folding Study',       'rare',     ['biology','computing'],                'neutral'),
('Amateur Spectroscopy',        'very_rare',['chemistry','physics'],                'neutral'),
('Radio Astronomy (Amateur)',   'very_rare',['astronomy','electronics'],            'neutral'),
('Telescope Mirror Grinding',   'very_rare',['astronomy','precision'],              'neutral'),
('Sundial Making',              'rare',     ['astronomy','precision'],              'neutral'),
('Antikythera Recreation',      'legendary',['history','precision'],                'neutral'),
('Clock Making / Horology',     'rare',     ['precision','mechanics'],              'neutral'),
('Pen Plotter Art',             'rare',     ['programming','drawing'],              'neutral'),
('MIDI Art Installation',       'very_rare',['music','programming','creativity'],   'neutral'),
('Circuit Bending',             'rare',     ['electronics','creativity'],           'neutral'),
('Drone Light Show (Hobby)',    'very_rare',['programming','electronics'],          'neutral'),
('Wearable Electronics',        'rare',     ['electronics','sewing'],               'neutral'),
('DIY Microscopy',              'uncommon', ['biology','electronics'],              'neutral'),
('DIY NAS / Home Server',       'uncommon', ['networking','programming'],           'neutral'),
('Darkweb Security Research',   'very_rare',['programming','hacking'],              'neutral'),
('AI Art Generation',           'common',   ['digital_art','creativity'],           'neutral'),
('Prompt Engineering',          'uncommon', ['programming','creativity'],           'neutral'),
# ── MISC UNIQUE ──────────────────────────────────────────────
('Sand Dune Ecology Study',     'rare',     ['biology','geology'],                  'neutral'),
('Sandstorm Photography',       'very_rare',['photography','endurance'],            'neutral'),
('Dead Language Decipherment',  'legendary',['languages','history','logic'],        'neutral'),
('Cuneiform Study',             'very_rare',['history','languages'],                'neutral'),
('Hieroglyphics Study',         'very_rare',['history','languages'],                'neutral'),
('Demotic Script Study',        'legendary',['history','languages'],                'neutral'),
('Forensic Genealogy',          'rare',     ['research','biology'],                 'neutral'),
('DNA / Ancestry Kit Hobbying','common',   ['biology','knowledge'],                'neutral'),
('Paranormal Writing',          'uncommon', ['writing','creativity'],               'neutral'),
('Cold Case Research',          'rare',     ['research','knowledge'],               'neutral'),
('True Crime Podcast Producing','uncommon', ['research','storytelling'],            'neutral'),
('Disaster Preparedness',       'common',   ['survival','organization'],            'neutral'),
('Bushfire Volunteer Prep',     'rare',     ['survival','teamwork'],                'good'),
('CERT Training (Hobby)',       'uncommon', ['first_aid','teamwork'],               'good'),
('Amateur Lifeguard Training',  'uncommon', ['swimming','first_aid'],               'good'),
('Competitive Cheer',           'uncommon', ['dancing','acrobatics','teamwork'],    'neutral'),
('Circus Clown School',         'rare',     ['acting','acrobatics','social'],       'neutral'),
('Street Photography Ethics',   'uncommon', ['photography','philosophy'],           'neutral'),
('Haul Video Making',           'common',   ['social','creativity'],                'neutral'),
('ASMR Creation (Advanced)',    'uncommon', ['audio_engineering','creativity'],     'neutral'),
('Sleep Study (Personal)',      'uncommon', ['biology','observation'],              'neutral'),
('Dream Journaling',            'common',   ['writing','introspection'],            'neutral'),
('Astral Projection Writing',   'uncommon', ['writing','introspection'],            'neutral'),
('Channelling (Hobby)',         'very_rare',['intuition','knowledge'],              'neutral'),
('Seance Hosting',              'rare',     ['social','acting'],                    'neutral'),
('Paranormal Investigation Leading','rare', ['leadership','knowledge','observation'],'neutral'),
('Competitive Dog Sport',       'rare',     ['animal_handling','agility'],          'neutral'),
('Sheep Dog Trialing',          'very_rare',['animal_handling','patience'],         'neutral'),
('Cat Agility Training',        'rare',     ['animal_handling','patience'],         'neutral'),
('Parrot Teaching',             'uncommon', ['animal_handling','patience'],         'neutral'),
('Capybara Farming (Hobby)',    'legendary',['animal_handling','knowledge'],        'neutral'),
('Bug Fighting (Insect)',       'very_rare',['animal_handling','knowledge'],        'neutral'),
('Competitive Duck Herding',    'legendary',['animal_handling','tactics'],          'neutral'),
('Ferret Racing',               'legendary',['animal_handling'],                    'neutral'),
('Rabbit Show Jumping',         'very_rare',['animal_handling','patience'],         'neutral'),
('Rabbit Agility',              'rare',     ['animal_handling','patience'],         'neutral'),
('Hamster Racing',              'rare',     ['animal_handling'],                    'neutral'),
('Fish Keeping Competition',    'uncommon', ['biology','knowledge'],                'neutral'),
]

existing_labels = {h['label'].lower() for h in d['hobbies']}
next_id = max(int(h['id'].split('-')[1]) for h in d['hobbies']) + 1
added = 0
for label, rarity, skills, alignment in RAW:
    if label.lower() in existing_labels:
        continue
    d['hobbies'].append({
        'id':        f'hobby-{next_id:05d}',
        'label':     label,
        'rarity':    rarity,
        'skills':    skills,
        'alignment': alignment,
    })
    existing_labels.add(label.lower())
    next_id += 1
    added += 1

with open(PATH, 'w', encoding='utf-8', newline='\n') as f:
    json.dump(d, f, ensure_ascii=False, indent=2)

print(f'Added {added} hobbies  →  total {len(d["hobbies"])}')
