#!/usr/bin/env python3
"""Expand hobbies to ~1500 and fix the duplicate 'dishwasher' occupation ID."""
import json, sys
sys.stdout.reconfigure(encoding='utf-8')

PATH = 'system/team-gen.json'
with open(PATH, encoding='utf-8') as f:
    d = json.load(f)

# ── 1. Fix duplicate occupation ID ────────────────────────────
seen_ids = set()
for o in d['occupations']:
    if o['id'] in seen_ids:
        o['id'] = o['id'] + '_2'
    seen_ids.add(o['id'])

# ── 2. Build new hobbies ───────────────────────────────────────
# Compact format: (label, rarity, [skills], alignment)
# rarity: common / uncommon / rare / very_rare / legendary
RAW = [
# ── VISUAL ARTS ───────────────────────────────────────────────
('Sketching',                   'common',   ['drawing','observation'],              'neutral'),
('Portrait Drawing',            'uncommon', ['drawing','observation'],              'neutral'),
('Caricature Drawing',          'rare',     ['drawing','humor'],                    'neutral'),
('Manga / Anime Drawing',       'uncommon', ['drawing','storytelling'],             'neutral'),
('Comics Creation',             'rare',     ['drawing','storytelling'],             'neutral'),
('Fantasy Art',                 'uncommon', ['drawing','creativity'],               'neutral'),
('Architectural Sketching',     'rare',     ['drawing','precision'],                'neutral'),
('Life Drawing',                'uncommon', ['drawing','observation'],              'neutral'),
('Watercolour Painting',        'uncommon', ['painting','patience'],                'neutral'),
('Oil Painting',                'uncommon', ['painting','patience'],                'neutral'),
('Acrylic Painting',            'common',   ['painting','creativity'],              'neutral'),
('Gouache Painting',            'rare',     ['painting','patience'],                'neutral'),
('Miniature Painting',          'uncommon', ['painting','precision','patience'],    'neutral'),
('Digital Painting',            'uncommon', ['drawing','digital_art'],              'neutral'),
('Concept Art',                 'rare',     ['drawing','creativity'],               'neutral'),
('Street Art / Graffiti',       'uncommon', ['drawing','agility'],                  'neutral'),
('Mural Painting',              'rare',     ['painting','climbing'],                'neutral'),
('Stencil Art',                 'uncommon', ['drawing','precision'],                'neutral'),
('Illustration',                'uncommon', ['drawing','storytelling'],             'neutral'),
('Plein Air Painting',          'uncommon', ['painting','observation'],             'neutral'),
('Abstract Painting',           'uncommon', ['painting','creativity'],              'neutral'),
('Pointillism',                 'very_rare',['painting','patience'],                'neutral'),
('Encaustic Art',               'very_rare',['painting','creativity'],              'neutral'),
('Clay Sculpture',              'uncommon', ['sculpting','patience'],               'neutral'),
('Stone Carving',               'rare',     ['sculpting','strength'],               'neutral'),
('Metal Sculpture',             'rare',     ['sculpting','welding'],                'neutral'),
('Wood Carving (Fine)',          'uncommon', ['sculpting','precision'],              'neutral'),
('Wire Sculpture',              'uncommon', ['sculpting','precision'],              'neutral'),
('Papier-Mâché',                'common',   ['sculpting','creativity'],             'neutral'),
('Resin Art',                   'uncommon', ['creativity','chemistry'],             'neutral'),
('Mosaics',                     'uncommon', ['patience','precision'],               'neutral'),
('Stained Glass Making',        'rare',     ['precision','patience'],               'neutral'),
('Glassblowing',                'very_rare',['sculpting','endurance'],              'neutral'),
('Pottery',                     'uncommon', ['sculpting','patience'],               'neutral'),
('Wheel Throwing',              'uncommon', ['sculpting','coordination'],           'neutral'),
('Ceramics (Advanced)',         'rare',     ['sculpting','precision'],              'neutral'),
('Linocut / Printmaking',       'uncommon', ['drawing','precision'],                'neutral'),
('Screen Printing',             'uncommon', ['precision','creativity'],             'neutral'),
('Etching',                     'rare',     ['drawing','chemistry'],                'neutral'),
('Letterpress Printing',        'very_rare',['precision','patience'],               'neutral'),
('Calligraphy (Latin)',         'uncommon', ['writing','patience'],                 'neutral'),
('Calligraphy (Arabic)',        'rare',     ['writing','patience'],                 'neutral'),
('Calligraphy (East Asian)',    'rare',     ['writing','patience'],                 'neutral'),
('Copperplate Calligraphy',     'rare',     ['writing','precision'],                'neutral'),
('Brush Lettering',             'uncommon', ['writing','precision'],                'neutral'),
('Origami',                     'common',   ['paper_folding','patience'],           'neutral'),
('Modular Origami',             'uncommon', ['paper_folding','patience'],           'neutral'),
('Kirigami',                    'uncommon', ['paper_folding','precision'],          'neutral'),
('Paper Marbling',              'rare',     ['creativity','patience'],              'neutral'),
('Decoupage',                   'uncommon', ['creativity','patience'],              'neutral'),
('Scrapbooking',                'common',   ['creativity','organization'],          'neutral'),
('Card Making',                 'common',   ['creativity','precision'],             'neutral'),
('Journaling (Art)',            'common',   ['drawing','writing'],                  'neutral'),
('Bullet Journaling',           'common',   ['organization','writing'],             'neutral'),
('Collage Art',                 'common',   ['creativity','observation'],           'neutral'),
('Pyrography (Wood Burning)',   'uncommon', ['precision','patience'],               'neutral'),
('Leather Tooling',             'uncommon', ['precision','leatherworking'],         'neutral'),
('Leatherworking',              'uncommon', ['precision','crafting'],               'neutral'),
('3D Modelling (Digital)',      'rare',     ['digital_art','spatial_reasoning'],    'neutral'),
('Animation (2D)',              'rare',     ['drawing','patience'],                 'neutral'),
('Animation (3D)',              'very_rare',['digital_art','spatial_reasoning'],    'neutral'),
('Stop-Motion Animation',       'rare',     ['patience','creativity'],              'neutral'),
('Photography (Portrait)',      'common',   ['photography','social'],               'neutral'),
('Photography (Wildlife)',      'uncommon', ['photography','patience','tracking'],  'neutral'),
('Photography (Street)',        'common',   ['photography','observation'],          'neutral'),
('Photography (Night)',         'uncommon', ['photography','patience'],             'neutral'),
('Photography (Macro)',         'rare',     ['photography','precision'],            'neutral'),
('Astrophotography',            'rare',     ['photography','astronomy'],            'neutral'),
('Film Photography',            'uncommon', ['photography','chemistry'],            'neutral'),
('Darkroom Photography',        'rare',     ['photography','chemistry'],            'neutral'),
('Drone Photography',           'uncommon', ['photography','piloting'],             'neutral'),
('Underwater Photography',      'rare',     ['photography','diving'],               'neutral'),
('Photo Editing / Retouching',  'common',   ['digital_art','photography'],          'neutral'),
('Fashion Photography',         'uncommon', ['photography','social'],               'neutral'),
('Zine Making',                 'uncommon', ['writing','drawing'],                  'neutral'),
('Graphic Design (Hobby)',      'uncommon', ['digital_art','creativity'],           'neutral'),
('Logo Design',                 'uncommon', ['digital_art','precision'],            'neutral'),
('Font Design / Typography',    'rare',     ['digital_art','precision'],            'neutral'),
('Tattoo Design',               'uncommon', ['drawing','creativity'],               'neutral'),
('Colouring Books (Hobby)',     'common',   ['patience'],                           'neutral'),
('Adult Colouring Books',       'common',   ['patience','creativity'],              'neutral'),
# ── TEXTILES & FIBRE ARTS ────────────────────────────────────
('Knitting',                    'common',   ['knitting','patience'],                'neutral'),
('Advanced Knitting',           'uncommon', ['knitting','patience'],                'neutral'),
('Sock Knitting',               'uncommon', ['knitting','precision'],               'neutral'),
('Lace Knitting',               'rare',     ['knitting','precision'],               'neutral'),
('Crocheting',                  'common',   ['crocheting','patience'],              'neutral'),
('Amigurumi (Crochet Animals)', 'uncommon', ['crocheting','creativity'],            'neutral'),
('Embroidery',                  'common',   ['embroidery','patience'],              'neutral'),
('Cross-Stitch',                'common',   ['embroidery','patience'],              'neutral'),
('Needlepoint',                 'uncommon', ['embroidery','patience'],              'neutral'),
('Blackwork Embroidery',        'rare',     ['embroidery','precision'],             'neutral'),
('Goldwork Embroidery',         'very_rare',['embroidery','precision'],             'neutral'),
('Macramé',                     'common',   ['knot_tying','creativity'],            'neutral'),
('Weaving',                     'uncommon', ['weaving','patience'],                 'neutral'),
('Tapestry Weaving',            'rare',     ['weaving','creativity'],               'neutral'),
('Card Weaving',                'rare',     ['weaving','precision'],                'neutral'),
('Spinning Fibre (Wheel)',      'rare',     ['weaving','patience'],                 'neutral'),
('Drop Spindle Spinning',       'uncommon', ['weaving','patience'],                 'neutral'),
('Felting (Wet)',               'uncommon', ['crafting','patience'],                'neutral'),
('Needle Felting',              'uncommon', ['crafting','precision'],               'neutral'),
('Sewing (General)',            'common',   ['sewing','precision'],                 'neutral'),
('Garment Sewing',              'uncommon', ['sewing','precision'],                 'neutral'),
('Pattern Drafting',            'rare',     ['sewing','mathematics'],               'neutral'),
('Costume Sewing',              'uncommon', ['sewing','creativity'],                'neutral'),
('Quilting',                    'uncommon', ['sewing','precision'],                 'neutral'),
('Patchwork',                   'common',   ['sewing','creativity'],                'neutral'),
('Rag Rug Making',              'uncommon', ['weaving','patience'],                 'neutral'),
('Dyeing Fabric (Natural)',     'uncommon', ['chemistry','crafting'],               'neutral'),
('Tie-Dyeing',                  'common',   ['crafting','creativity'],              'neutral'),
('Block Printing on Fabric',    'uncommon', ['printing','precision'],               'neutral'),
('Batik',                       'rare',     ['crafting','patience'],                'neutral'),
('Lucet Cord Making',           'very_rare',['knot_tying','patience'],              'neutral'),
# ── MUSIC ────────────────────────────────────────────────────
('Piano',                       'uncommon', ['music','precision','patience'],       'neutral'),
('Classical Guitar',            'uncommon', ['music','precision'],                  'neutral'),
('Acoustic Guitar',             'common',   ['music','coordination'],               'neutral'),
('Electric Guitar',             'uncommon', ['music','coordination'],               'neutral'),
('Bass Guitar',                 'uncommon', ['music','coordination'],               'neutral'),
('Drums',                       'uncommon', ['music','coordination','rhythm'],      'neutral'),
('Electronic Drum Kit',         'uncommon', ['music','coordination'],               'neutral'),
('Violin',                      'uncommon', ['music','precision','patience'],       'neutral'),
('Viola',                       'rare',     ['music','precision'],                  'neutral'),
('Cello',                       'rare',     ['music','precision'],                  'neutral'),
('Double Bass',                 'rare',     ['music','strength'],                   'neutral'),
('Harp',                        'very_rare',['music','precision','patience'],       'neutral'),
('Flute',                       'uncommon', ['music','precision'],                  'neutral'),
('Clarinet',                    'uncommon', ['music','precision'],                  'neutral'),
('Oboe',                        'rare',     ['music','precision'],                  'neutral'),
('Bassoon',                     'very_rare',['music','precision'],                  'neutral'),
('Saxophone',                   'uncommon', ['music','coordination'],               'neutral'),
('Trumpet',                     'uncommon', ['music','endurance'],                  'neutral'),
('Trombone',                    'uncommon', ['music','coordination'],               'neutral'),
('French Horn',                 'rare',     ['music','precision'],                  'neutral'),
('Tuba',                        'rare',     ['music','endurance'],                  'neutral'),
('Euphonium',                   'rare',     ['music','endurance'],                  'neutral'),
('Recorder',                    'common',   ['music','coordination'],               'neutral'),
('Banjo',                       'uncommon', ['music','coordination'],               'neutral'),
('Mandolin',                    'uncommon', ['music','precision'],                  'neutral'),
('Ukulele',                     'common',   ['music','coordination'],               'neutral'),
('Lute',                        'very_rare',['music','precision'],                  'neutral'),
('Sitar',                       'very_rare',['music','patience'],                   'neutral'),
('Tabla (Indian Drums)',        'rare',     ['music','rhythm'],                     'neutral'),
('Djembe',                      'uncommon', ['music','rhythm'],                     'neutral'),
('Bongos',                      'common',   ['music','rhythm'],                     'neutral'),
('Accordion',                   'uncommon', ['music','coordination'],               'neutral'),
('Concertina',                  'rare',     ['music','coordination'],               'neutral'),
('Harmonica',                   'common',   ['music','breath_control'],             'neutral'),
('Ocarina',                     'uncommon', ['music','breath_control'],             'neutral'),
('Bagpipes',                    'very_rare',['music','breath_control','endurance'], 'neutral'),
('Didgeridoo',                  'very_rare',['music','breath_control'],             'neutral'),
('Theremin',                    'very_rare',['music','coordination'],               'neutral'),
('Synthesizer',                 'uncommon', ['music','electronics'],                'neutral'),
('Music Production (DAW)',      'uncommon', ['music','digital_art'],                'neutral'),
('Music Composition',           'rare',     ['music','creativity'],                 'neutral'),
('Music Theory Study',          'uncommon', ['music','mathematics'],                'neutral'),
('DJing',                       'uncommon', ['music','rhythm'],                     'neutral'),
('Turntablism (Scratching)',    'rare',     ['music','coordination'],               'neutral'),
('Beatboxing',                  'uncommon', ['music','rhythm'],                     'neutral'),
('Singing (General)',           'common',   ['singing','breath_control'],           'neutral'),
('Choir Singing',               'uncommon', ['singing','social'],                   'neutral'),
('Opera Singing',               'rare',     ['singing','endurance'],                'neutral'),
('Barbershop Singing',          'rare',     ['singing','social'],                   'neutral'),
('A Cappella',                  'uncommon', ['singing','coordination'],             'neutral'),
('Karaoke',                     'common',   ['singing','social'],                   'neutral'),
('Songwriting',                 'uncommon', ['music','writing'],                    'neutral'),
('Playing in a Band',           'uncommon', ['music','social','coordination'],      'neutral'),
('Folk Music',                  'uncommon', ['music','history'],                    'neutral'),
('Jazz Improvisation',          'rare',     ['music','creativity'],                 'neutral'),
('Busking',                     'uncommon', ['music','social'],                     'neutral'),
('Conducting',                  'very_rare',['music','leadership'],                 'neutral'),
('Score Reading',               'rare',     ['music','reading'],                    'neutral'),
('Ear Training',                'uncommon', ['music','perception'],                 'neutral'),
# ── DANCE ────────────────────────────────────────────────────
('Ballet',                      'uncommon', ['dancing','balance','agility'],        'neutral'),
('Contemporary Dance',          'uncommon', ['dancing','agility','creativity'],     'neutral'),
('Jazz Dance',                  'uncommon', ['dancing','agility'],                  'neutral'),
('Tap Dancing',                 'uncommon', ['dancing','coordination','rhythm'],    'neutral'),
('Hip-Hop Dance',               'uncommon', ['dancing','agility'],                  'neutral'),
('Breakdancing',                'uncommon', ['dancing','agility','acrobatics'],     'neutral'),
('Popping and Locking',         'uncommon', ['dancing','coordination'],             'neutral'),
('Krump',                       'rare',     ['dancing','agility'],                  'neutral'),
('Waltz',                       'uncommon', ['dancing','coordination'],             'neutral'),
('Tango',                       'uncommon', ['dancing','coordination'],             'neutral'),
('Foxtrot',                     'uncommon', ['dancing','coordination'],             'neutral'),
('Quickstep',                   'rare',     ['dancing','agility'],                  'neutral'),
('Viennese Waltz',              'rare',     ['dancing','coordination','endurance'], 'neutral'),
('Salsa',                       'common',   ['dancing','coordination'],             'neutral'),
('Bachata',                     'common',   ['dancing','coordination'],             'neutral'),
('Merengue',                    'uncommon', ['dancing','coordination'],             'neutral'),
('Cha-Cha',                     'uncommon', ['dancing','coordination'],             'neutral'),
('Rumba',                       'uncommon', ['dancing','coordination'],             'neutral'),
('Samba (Dance)',               'uncommon', ['dancing','agility'],                  'neutral'),
('Paso Doble',                  'rare',     ['dancing','coordination'],             'neutral'),
('Flamenco',                    'rare',     ['dancing','stamina','coordination'],   'neutral'),
('Irish Step Dancing',          'rare',     ['dancing','agility','coordination'],   'neutral'),
('Scottish Country Dancing',    'rare',     ['dancing','coordination'],             'neutral'),
('Bollywood Dance',             'uncommon', ['dancing','agility'],                  'neutral'),
('Bharatanatyam',               'rare',     ['dancing','agility','endurance'],      'neutral'),
('Kathak',                      'rare',     ['dancing','coordination'],             'neutral'),
('Swing Dancing (Lindy Hop)',   'uncommon', ['dancing','coordination'],             'neutral'),
('Charleston (Dance)',          'uncommon', ['dancing','agility'],                  'neutral'),
('Pole Dancing',                'uncommon', ['dancing','strength','agility'],       'neutral'),
('Aerial Silks',                'rare',     ['acrobatics','strength','agility'],    'neutral'),
('Aerial Hoop (Lyra)',          'rare',     ['acrobatics','strength'],              'neutral'),
('Zumba',                       'common',   ['dancing','endurance'],                'neutral'),
('K-Pop Dance',                 'uncommon', ['dancing','agility'],                  'neutral'),
('Line Dancing',                'common',   ['dancing','coordination'],             'neutral'),
('Belly Dancing',               'uncommon', ['dancing','coordination'],             'neutral'),
('Hula Dancing',                'uncommon', ['dancing','coordination'],             'neutral'),
('Poi Spinning',                'uncommon', ['dancing','coordination'],             'neutral'),
('Staff Spinning (Flow Arts)',  'uncommon', ['coordination','agility'],             'neutral'),
('Fire Dancing',                'rare',     ['coordination','agility'],             'neutral'),
('Competitive Dance',           'rare',     ['dancing','endurance','agility'],      'neutral'),
# ── COOKING & FOOD ────────────────────────────────────────────
('Bread Baking',                'common',   ['cooking','patience'],                 'neutral'),
('Sourdough Baking',            'uncommon', ['cooking','chemistry','patience'],     'neutral'),
('Pastry Making',               'uncommon', ['cooking','precision'],                'neutral'),
('Cake Decorating',             'uncommon', ['cooking','precision','creativity'],   'neutral'),
('Sugar Art',                   'rare',     ['cooking','precision'],                'neutral'),
('Chocolatiering',              'rare',     ['cooking','precision','chemistry'],    'neutral'),
('Candy Making',                'uncommon', ['cooking','chemistry'],                'neutral'),
('Ice Cream Making',            'uncommon', ['cooking','chemistry'],                'neutral'),
('Gelato Making',               'rare',     ['cooking','chemistry'],                'neutral'),
('BBQ / Grilling',              'common',   ['cooking','fire_making'],              'neutral'),
('Smoking Meat',                'uncommon', ['cooking','patience'],                 'neutral'),
('Charcuterie Board Making',    'common',   ['cooking','creativity'],               'neutral'),
('Cheesemaking',                'uncommon', ['cooking','chemistry','patience'],     'neutral'),
('Home Brewing (Beer)',         'uncommon', ['brewing','chemistry'],                'neutral'),
('Wine Making',                 'uncommon', ['brewing','chemistry'],                'neutral'),
('Mead Making',                 'uncommon', ['brewing','chemistry'],                'neutral'),
('Cider Making',                'uncommon', ['brewing','chemistry'],                'neutral'),
('Kombucha Brewing',            'common',   ['brewing','chemistry'],                'neutral'),
('Kefir / Fermented Foods',    'uncommon', ['cooking','chemistry'],                 'neutral'),
('Kimchi Making',               'uncommon', ['cooking','chemistry'],                'neutral'),
('Sauerkraut / Pickling',       'common',   ['cooking','chemistry'],                'neutral'),
('Sushi Making',                'rare',     ['cooking','precision'],                'neutral'),
('Ramen Cooking',               'uncommon', ['cooking','patience'],                 'neutral'),
('Dim Sum Making',              'rare',     ['cooking','precision'],                'neutral'),
('Pasta Making (Fresh)',        'uncommon', ['cooking','precision'],                'neutral'),
('Pizza Making (Artisan)',      'common',   ['cooking','precision'],                'neutral'),
('Molecular Gastronomy',        'very_rare',['cooking','chemistry','precision'],    'neutral'),
('Food Styling',                'rare',     ['cooking','creativity','photography'], 'neutral'),
('Food Photography (Hobby)',    'uncommon', ['photography','cooking'],              'neutral'),
('Cocktail Mixing',             'common',   ['cooking','chemistry'],                'neutral'),
('Craft Beer Tasting',          'common',   ['taste_discrimination'],               'neutral'),
('Wine Tasting',                'uncommon', ['taste_discrimination'],               'neutral'),
('Sake Tasting',                'rare',     ['taste_discrimination'],               'neutral'),
('Whisky Appreciation',        'uncommon', ['taste_discrimination'],               'neutral'),
('Coffee Roasting',             'uncommon', ['cooking','chemistry','patience'],     'neutral'),
('Specialty Coffee (Barista)',  'common',   ['cooking','precision'],                'neutral'),
('Tea Ceremony',                'uncommon', ['patience','culture'],                 'neutral'),
('Vegan Cooking',               'common',   ['cooking','nutrition_knowledge'],      'neutral'),
('Raw Food Preparation',        'uncommon', ['cooking','nutrition_knowledge'],      'neutral'),
('Fermentation (General)',      'uncommon', ['cooking','chemistry'],                'neutral'),
('Jam / Preserve Making',       'common',   ['cooking','chemistry'],                'neutral'),
('Canning and Bottling',        'uncommon', ['cooking','chemistry'],                'neutral'),
('Spice Blending',              'uncommon', ['cooking','chemistry'],                'neutral'),
('Meal Prep',                   'common',   ['cooking','organization'],             'neutral'),
('Recipe Development',          'uncommon', ['cooking','creativity'],               'neutral'),
('Cooking for Competition',     'rare',     ['cooking','endurance'],                'neutral'),
('Street Food Cooking',         'uncommon', ['cooking','social'],                   'neutral'),
('Outdoor / Camp Cooking',      'common',   ['cooking','survival','fire_making'],   'neutral'),
('Dutch Oven Cooking',          'uncommon', ['cooking','fire_making'],              'neutral'),
('Cast Iron Cooking',           'uncommon', ['cooking'],                            'neutral'),
# ── GAMING ────────────────────────────────────────────────────
('Video Games (FPS)',           'common',   ['reflexes','tactics','coordination'],  'neutral'),
('Video Games (RPG)',           'common',   ['strategy','knowledge'],               'neutral'),
('Video Games (RTS)',           'common',   ['strategy','multi_tasking'],           'neutral'),
('Video Games (MOBA)',          'common',   ['strategy','coordination','tactics'],  'neutral'),
('Video Games (MMO)',           'common',   ['strategy','social'],                  'neutral'),
('Video Games (Battle Royale)', 'common',   ['reflexes','tactics','survival'],      'neutral'),
('Video Games (Fighting)',      'common',   ['reflexes','coordination'],            'neutral'),
('Video Games (Sports)',        'common',   ['coordination'],                       'neutral'),
('Video Games (Racing)',        'common',   ['coordination','reflexes'],            'neutral'),
('Video Games (Horror)',        'common',   ['endurance','perception'],             'neutral'),
('Video Games (Survival)',      'common',   ['survival','strategy'],                'neutral'),
('Video Games (Puzzle)',        'common',   ['puzzle_solving','patience'],          'neutral'),
('Video Games (Platformer)',    'common',   ['coordination','reflexes'],            'neutral'),
('Visual Novels',               'common',   ['reading','knowledge'],                'neutral'),
('Rhythm Games',                'uncommon', ['rhythm','coordination'],              'neutral'),
('Speedrunning',                'rare',     ['reflexes','strategy','patience'],     'neutral'),
('Game Streaming',              'uncommon', ['social','digital_art'],               'neutral'),
('Game Modding',                'rare',     ['programming','creativity'],           'neutral'),
('Retro Gaming',                'uncommon', ['knowledge','patience'],               'neutral'),
('Tabletop RPG (D&D)',          'uncommon', ['strategy','storytelling','social'],   'neutral'),
('Tabletop RPG (Pathfinder)',   'uncommon', ['strategy','mathematics','social'],    'neutral'),
('Tabletop RPG (Call of Cthulhu)','rare',  ['strategy','knowledge','social'],      'neutral'),
('Tabletop RPG (WFRP)',         'rare',     ['strategy','knowledge','social'],      'neutral'),
('Tabletop RPG (Star Wars)',    'uncommon', ['strategy','social'],                  'neutral'),
('Board Games (Strategy)',      'common',   ['strategy','patience'],                'neutral'),
('Board Games (Cooperative)',   'common',   ['strategy','social','teamwork'],       'neutral'),
('Board Games (Worker Placement)','uncommon',['strategy','planning'],              'neutral'),
('Deck Building Games',         'uncommon', ['strategy','planning'],                'neutral'),
('Legacy Board Games',          'rare',     ['strategy','storytelling'],            'neutral'),
('Magic: The Gathering',        'uncommon', ['strategy','memory'],                  'neutral'),
('Pokémon TCG',                 'common',   ['strategy','memory'],                  'neutral'),
('Yu-Gi-Oh!',                   'uncommon', ['strategy','memory'],                  'neutral'),
('Flesh and Blood TCG',         'rare',     ['strategy','memory'],                  'neutral'),
('Chess',                       'common',   ['strategy','patience','planning'],     'neutral'),
('Advanced Chess',              'uncommon', ['strategy','planning','memory'],       'neutral'),
('Go (Baduk/Weiqi)',            'uncommon', ['strategy','patience','planning'],     'neutral'),
('Shogi',                       'rare',     ['strategy','patience'],                'neutral'),
('Xiangqi (Chinese Chess)',     'uncommon', ['strategy','patience'],                'neutral'),
('Backgammon',                  'uncommon', ['strategy','probability'],             'neutral'),
('Mah-jong',                    'uncommon', ['strategy','memory'],                  'neutral'),
('Poker',                       'common',   ['strategy','deception','probability'], 'neutral'),
('Bridge (Card Game)',          'rare',     ['strategy','memory','social'],         'neutral'),
('Cribbage',                    'uncommon', ['mathematics','strategy'],             'neutral'),
('Warhammer 40K (Tabletop)',    'rare',     ['strategy','painting','patience'],     'neutral'),
('Age of Sigmar',               'rare',     ['strategy','painting'],                'neutral'),
('Miniature Wargaming (General)','uncommon',['strategy','patience'],               'neutral'),
('Miniature Painting (Wargames)','uncommon',['painting','precision'],              'neutral'),
('Dungeons & Dragons DMing',    'rare',     ['storytelling','strategy','social'],   'neutral'),
('LARP (Live Action Roleplay)', 'rare',     ['acting','social','physical_training'],'neutral'),
('Escape Rooms',                'common',   ['puzzle_solving','teamwork'],          'neutral'),
('Puzzle Design / Creation',    'rare',     ['puzzle_solving','creativity'],        'neutral'),
('Speed Cubing (Rubik\'s Cube)','uncommon',['reflexes','memory','pattern_recognition'],'neutral'),
('Twisty Puzzles (General)',    'uncommon', ['spatial_reasoning','patience'],       'neutral'),
('Competitive Crossword',       'rare',     ['vocabulary','memory'],                'neutral'),
# ── COLLECTING ────────────────────────────────────────────────
('Stamp Collecting',            'uncommon', ['knowledge','patience','organization'],'neutral'),
('Coin Collecting',             'uncommon', ['knowledge','patience','organization'],'neutral'),
('Banknote Collecting',         'rare',     ['knowledge','patience'],               'neutral'),
('Vintage Toy Collecting',      'uncommon', ['knowledge','patience'],               'neutral'),
('Action Figure Collecting',    'common',   ['knowledge','organization'],           'neutral'),
('Funko Pop Collecting',        'common',   ['organization'],                       'neutral'),
('Vinyl Record Collecting',     'uncommon', ['music','knowledge'],                  'neutral'),
('Cassette Tape Collecting',    'rare',     ['knowledge'],                          'neutral'),
('CD Collecting',               'uncommon', ['music','knowledge'],                  'neutral'),
('Book Collecting (First Ed.)', 'rare',     ['knowledge','patience'],               'neutral'),
('Comic Book Collecting',       'uncommon', ['knowledge','organization'],           'neutral'),
('Sports Card Collecting',      'common',   ['knowledge','organization'],           'neutral'),
('Pokémon Card Collecting',     'common',   ['knowledge','organization'],           'neutral'),
('Antique Collecting',          'uncommon', ['knowledge','patience'],               'neutral'),
('Art Collecting',              'very_rare',['knowledge','negotiation'],            'neutral'),
('Fossil Collecting',           'uncommon', ['knowledge','survival'],               'neutral'),
('Rock and Mineral Collecting', 'uncommon', ['knowledge','geology'],                'neutral'),
('Meteorite Hunting',           'very_rare',['knowledge','navigation'],             'neutral'),
('Wine Cellar Curation',        'rare',     ['taste_discrimination','knowledge'],   'neutral'),
('Watch Collecting',            'rare',     ['knowledge','precision'],              'neutral'),
('Pen Collecting',              'uncommon', ['knowledge','writing'],                'neutral'),
('Knife Collecting',            'uncommon', ['knowledge','melee'],                  'neutral'),
('Sneaker Collecting',          'common',   ['knowledge','fashion'],                'neutral'),
('Vintage Clothing Collecting', 'uncommon', ['knowledge','fashion'],                'neutral'),
('Militaria Collecting',        'rare',     ['knowledge','history'],                'neutral'),
('Historical Artifacts',        'rare',     ['knowledge','history'],                'neutral'),
('Seashell Collecting',         'common',   ['knowledge','diving'],                 'neutral'),
('Butterfly Collecting',        'uncommon', ['knowledge','patience','tracking'],    'neutral'),
('Trading Card Games (General)','common',  ['strategy','memory'],                  'neutral'),
('Board Game Collection',       'common',   ['strategy','organization'],            'neutral'),
('Hot Wheels / Die-Cast Cars',  'common',   ['knowledge','organization'],           'neutral'),
# ── TECHNOLOGY & DIY ──────────────────────────────────────────
('Web Development (Hobby)',     'uncommon', ['programming','creativity'],           'neutral'),
('Game Development (Indie)',    'rare',     ['programming','creativity'],           'neutral'),
('App Development (Mobile)',    'uncommon', ['programming','creativity'],           'neutral'),
('Python Scripting',            'uncommon', ['programming','problem_solving'],      'neutral'),
('Open Source Contributing',    'rare',     ['programming','teamwork'],             'neutral'),
('Competitive Programming',     'very_rare',['programming','mathematics'],          'neutral'),
('Cybersecurity (CTF)',         'very_rare',['programming','problem_solving','hacking'],'neutral'),
('Network Homelab',             'rare',     ['networking','problem_solving'],       'neutral'),
('Arduino / Microcontrollers',  'uncommon', ['electronics','programming'],          'neutral'),
('Raspberry Pi Projects',       'uncommon', ['electronics','programming'],          'neutral'),
('Electronics (Hobby)',         'uncommon', ['electronics','problem_solving'],      'neutral'),
('Circuit Board Design',        'rare',     ['electronics','precision'],            'neutral'),
('Soldering',                   'uncommon', ['electronics','precision'],            'neutral'),
('3D Printing',                 'uncommon', ['digital_art','problem_solving'],      'neutral'),
('CNC Routing',                 'rare',     ['precision','programming'],            'neutral'),
('Laser Cutting',               'uncommon', ['precision','creativity'],             'neutral'),
('Home Automation / IoT',       'uncommon', ['electronics','programming'],          'neutral'),
('Robotics (Hobby)',            'rare',     ['electronics','programming','engineering'],'neutral'),
('Drone Building',              'uncommon', ['electronics','engineering'],          'neutral'),
('Ham Radio (Amateur)',         'uncommon', ['electronics','communication'],        'neutral'),
('Morse Code',                  'rare',     ['communication','memory'],             'neutral'),
('Mechanical Keyboard Building','uncommon', ['electronics','precision'],            'neutral'),
('PC Building',                 'common',   ['electronics','problem_solving'],      'neutral'),
('Retro Computing',             'rare',     ['electronics','history'],              'neutral'),
('Emulation / ROM Hacking',     'rare',     ['programming','knowledge'],            'neutral'),
('Lock Sport',                  'uncommon', ['lockpicking','problem_solving'],      'neutral'),
('Pen Testing (CTF / Legal)',   'very_rare',['programming','hacking'],              'neutral'),
('Smart Home Setup',            'uncommon', ['electronics','programming'],          'neutral'),
('Solar / Off-Grid Projects',   'rare',     ['electronics','engineering','survival'],'neutral'),
('Woodworking',                 'uncommon', ['carpentry','precision'],              'neutral'),
('Hand Tool Woodworking',       'uncommon', ['carpentry','patience'],               'neutral'),
('Furniture Making',            'rare',     ['carpentry','precision'],              'neutral'),
('Luthiery (Instrument Making)','very_rare',['carpentry','music','precision'],      'neutral'),
('Blacksmithing (Hobby)',       'rare',     ['metalworking','strength','endurance'],'neutral'),
('Knife Making',                'rare',     ['metalworking','precision'],           'neutral'),
('Axe Making',                  'rare',     ['metalworking','precision'],           'neutral'),
('Chainmaille Armour',          'uncommon', ['metalworking','patience'],            'neutral'),
('Candle Making',               'common',   ['chemistry','creativity'],             'neutral'),
('Soap Making',                 'common',   ['chemistry','creativity'],             'neutral'),
('Resin Casting',               'uncommon', ['chemistry','creativity'],             'neutral'),
('Taxidermy (Hobby)',           'very_rare',['biology','precision','patience'],     'neutral'),
# ── NATURE & GARDENING ────────────────────────────────────────
('Vegetable Gardening',         'common',   ['gardening','botany'],                 'neutral'),
('Flower Gardening',            'common',   ['gardening','botany'],                 'neutral'),
('Herb Gardening',              'common',   ['gardening','herbalism','botany'],     'neutral'),
('Fruit Tree Gardening',        'uncommon', ['gardening','botany'],                 'neutral'),
('Container Gardening',         'common',   ['gardening','botany'],                 'neutral'),
('Raised Bed Gardening',        'common',   ['gardening','botany'],                 'neutral'),
('Permaculture',                'rare',     ['gardening','ecology','survival'],     'neutral'),
('Bonsai',                      'uncommon', ['gardening','patience','precision'],   'neutral'),
('Terrarium Building',          'common',   ['gardening','creativity'],             'neutral'),
('Aquarium Keeping (Freshwater)','common',  ['biology','patience'],                 'neutral'),
('Aquarium Keeping (Marine)',   'rare',     ['biology','chemistry'],                'neutral'),
('Birdwatching',                'common',   ['observation','patience'],             'neutral'),
('Bird Photography',            'uncommon', ['photography','observation','patience'],'neutral'),
('Astronomy',                   'uncommon', ['observation','mathematics','physics'],'neutral'),
('Amateur Astronomy (Visual)',  'uncommon', ['observation','patience'],             'neutral'),
('Meteorology (Hobby)',         'uncommon', ['observation','mathematics'],          'neutral'),
('Geology (Hobby)',             'uncommon', ['observation','geology'],              'neutral'),
('Fossil Hunting',              'uncommon', ['observation','geology'],              'neutral'),
('Mushroom Foraging',           'uncommon', ['foraging','botany','survival'],       'neutral'),
('Wild Herb Foraging',          'uncommon', ['foraging','herbalism','survival'],    'neutral'),
('Beekeeping',                  'uncommon', ['patience','biology'],                 'neutral'),
('Composting',                  'common',   ['gardening','chemistry'],              'neutral'),
('Worm Farming / Vermicomposting','uncommon',['gardening','biology'],              'neutral'),
('Mushroom Cultivation',        'uncommon', ['biology','chemistry'],                'neutral'),
('Orchid Growing',              'uncommon', ['botany','patience'],                  'neutral'),
('Cactus Collecting',           'common',   ['botany'],                             'neutral'),
('Carnivorous Plant Growing',   'uncommon', ['botany','biology'],                   'neutral'),
('Insect Study (Entomology)',    'rare',     ['biology','observation'],              'neutral'),
('Lepidopterology (Butterflies)','rare',    ['biology','observation'],              'neutral'),
('Nature Journaling',           'common',   ['observation','drawing'],              'neutral'),
('Pond Keeping',                'uncommon', ['biology','gardening'],                'neutral'),
('Wildlife Tracking',           'rare',     ['tracking','observation','survival'],  'neutral'),
('Nature Photography',          'uncommon', ['photography','observation'],          'neutral'),
('Lichen Study',                'very_rare',['biology','observation'],              'neutral'),
('Tide Pooling',                'uncommon', ['biology','observation'],              'neutral'),
('Seashore Ecology',            'rare',     ['biology','observation'],              'neutral'),
# ── ANIMALS & PETS ────────────────────────────────────────────
('Dog Training (Advanced)',     'uncommon', ['animal_handling','patience'],         'neutral'),
('Dog Agility Competition',     'uncommon', ['animal_handling','agility'],          'neutral'),
('Dog Shows (Conformation)',    'rare',     ['animal_handling','knowledge'],        'neutral'),
('Cat Fancy',                   'uncommon', ['animal_handling','knowledge'],        'neutral'),
('Horse Riding (Show Jumping)', 'rare',     ['equestrian','agility'],               'neutral'),
('Horse Riding (Dressage)',     'rare',     ['equestrian','patience'],              'neutral'),
('Horse Riding (Western)',      'uncommon', ['equestrian'],                         'neutral'),
('Falconry',                    'very_rare',['animal_handling','patience'],         'neutral'),
('Pigeon Racing',               'rare',     ['animal_handling','navigation'],       'neutral'),
('Reptile Keeping',             'uncommon', ['animal_handling','biology'],          'neutral'),
('Exotic Bird Keeping',         'uncommon', ['animal_handling','biology'],          'neutral'),
('Tropical Fish Keeping',       'common',   ['biology','chemistry'],                'neutral'),
('Koi Pond Keeping',            'uncommon', ['biology','gardening'],                'neutral'),
('Animal Rescue Volunteering',  'common',   ['animal_handling','medicine'],         'good'),
('Wildlife Rehabilitation',     'rare',     ['animal_handling','medicine','biology'],'good'),
('Dog Obedience Training',      'common',   ['animal_handling','patience'],         'neutral'),
('Tracking Dogs',               'rare',     ['animal_handling','tracking'],         'neutral'),
('Cattle Herding (Hobby)',      'rare',     ['animal_handling','agility'],          'neutral'),
# ── WRITING & LITERATURE ─────────────────────────────────────
('Novel Writing',               'uncommon', ['writing','storytelling','creativity'],'neutral'),
('Short Story Writing',         'uncommon', ['writing','storytelling'],             'neutral'),
('Poetry',                      'uncommon', ['writing','creativity'],               'neutral'),
('Slam Poetry',                 'uncommon', ['writing','public_speaking'],          'neutral'),
('Screenwriting',               'rare',     ['writing','storytelling'],             'neutral'),
('Playwriting',                 'rare',     ['writing','storytelling'],             'neutral'),
('Song Lyrics Writing',         'uncommon', ['writing','music'],                    'neutral'),
('Fan Fiction Writing',         'common',   ['writing','creativity'],               'neutral'),
('Journaling',                  'common',   ['writing','introspection'],            'neutral'),
('Blogging',                    'common',   ['writing','social'],                   'neutral'),
('Vlogging / YouTube',          'common',   ['social','creativity'],                'neutral'),
('Podcast Making',              'uncommon', ['social','storytelling'],              'neutral'),
('Technical Writing (Hobby)',   'uncommon', ['writing','knowledge'],                'neutral'),
('Book Club Participation',     'common',   ['reading','social'],                   'neutral'),
('Literary Analysis',           'uncommon', ['reading','knowledge'],                'neutral'),
('Reading (Sci-Fi)',            'common',   ['reading','knowledge'],                'neutral'),
('Reading (Fantasy)',           'common',   ['reading','creativity'],               'neutral'),
('Reading (History)',           'common',   ['reading','knowledge'],                'neutral'),
('Reading (Crime Thrillers)',   'common',   ['reading','knowledge'],                'neutral'),
('Reading (Horror)',            'common',   ['reading','endurance'],                'neutral'),
('Reading (Philosophy)',        'uncommon', ['reading','knowledge'],                'neutral'),
('Reading (Science)',           'uncommon', ['reading','knowledge'],                'neutral'),
('Translation (Hobby)',         'rare',     ['languages','writing'],                'neutral'),
('Learning Latin',              'rare',     ['languages','history'],                'neutral'),
('Learning Ancient Greek',      'very_rare',['languages','history'],                'neutral'),
('Learning Sanskrit',           'very_rare',['languages','history'],                'neutral'),
('Learning Esperanto',          'rare',     ['languages'],                          'neutral'),
('Learning Klingon',            'legendary',['languages','knowledge'],              'neutral'),
('Linguistics Study',           'rare',     ['languages','knowledge'],              'neutral'),
# ── LANGUAGE LEARNING ────────────────────────────────────────
('Learning English (Hobby)',    'common',   ['languages'],                          'neutral'),
('Learning Spanish',            'common',   ['languages'],                          'neutral'),
('Learning French',             'common',   ['languages'],                          'neutral'),
('Learning German',             'common',   ['languages'],                          'neutral'),
('Learning Italian',            'uncommon', ['languages'],                          'neutral'),
('Learning Japanese',           'uncommon', ['languages'],                          'neutral'),
('Learning Korean',             'uncommon', ['languages'],                          'neutral'),
('Learning Mandarin',           'uncommon', ['languages'],                          'neutral'),
('Learning Arabic',             'rare',     ['languages'],                          'neutral'),
('Learning Russian',            'uncommon', ['languages'],                          'neutral'),
('Learning Portuguese',         'uncommon', ['languages'],                          'neutral'),
('Learning Dutch',              'uncommon', ['languages'],                          'neutral'),
('Learning Swedish',            'uncommon', ['languages'],                          'neutral'),
('Learning Norwegian',          'uncommon', ['languages'],                          'neutral'),
('Learning Polish',             'rare',     ['languages'],                          'neutral'),
('Learning Hindi',              'uncommon', ['languages'],                          'neutral'),
('Learning Turkish',            'rare',     ['languages'],                          'neutral'),
('Learning Thai',               'rare',     ['languages'],                          'neutral'),
('Learning Vietnamese',         'rare',     ['languages'],                          'neutral'),
('Learning Hebrew',             'rare',     ['languages'],                          'neutral'),
('Learning Persian/Farsi',      'rare',     ['languages'],                          'neutral'),
('Learning Swahili',            'rare',     ['languages'],                          'neutral'),
('Learning Welsh',              'rare',     ['languages','history'],                'neutral'),
('Learning Gaelic',             'rare',     ['languages','history'],                'neutral'),
('Sign Language (ASL)',         'uncommon', ['languages','social'],                 'neutral'),
('Sign Language (BSL)',         'uncommon', ['languages','social'],                 'neutral'),
# ── SPIRITUALITY & WELLNESS ──────────────────────────────────
('Meditation (General)',        'common',   ['meditation','endurance'],             'neutral'),
('Zen Meditation',              'uncommon', ['meditation','patience'],              'neutral'),
('Vipassana Meditation',        'uncommon', ['meditation','endurance'],             'neutral'),
('Transcendental Meditation',   'uncommon', ['meditation','patience'],              'neutral'),
('Mindfulness Practice',        'common',   ['meditation','endurance'],             'neutral'),
('Breathwork (Wim Hof)',        'uncommon', ['breath_control','endurance'],         'neutral'),
('Pranayama',                   'uncommon', ['breath_control','meditation'],        'neutral'),
('Qi Gong',                     'uncommon', ['meditation','agility'],               'neutral'),
('Tai Chi (General)',           'common',   ['meditation','agility','balance'],     'neutral'),
('Tai Chi (Advanced)',          'rare',     ['meditation','agility'],               'neutral'),
('Tarot Reading',               'uncommon', ['knowledge','intuition'],              'neutral'),
('Astrology Study',             'uncommon', ['knowledge','mathematics'],            'neutral'),
('Numerology Study',            'uncommon', ['knowledge','mathematics'],            'neutral'),
('Rune Reading',                'rare',     ['knowledge','history'],                'neutral'),
('Crystal Healing',             'uncommon', ['knowledge'],                          'neutral'),
('Herbalism Study',             'uncommon', ['herbalism','biology'],                'neutral'),
('Natural Medicine Study',      'uncommon', ['medicine','herbalism'],               'neutral'),
('Forest Bathing (Shinrin-yoku)','common',  ['meditation','observation'],           'neutral'),
('Nature Therapy',              'common',   ['meditation','observation'],           'neutral'),
('Journaling (Gratitude)',      'common',   ['writing','meditation'],               'neutral'),
('Sound Bath Participation',    'uncommon', ['meditation'],                         'neutral'),
('Shamanic Practice (Hobby)',   'very_rare',['meditation','knowledge'],             'neutral'),
('Astral Projection Practice',  'very_rare',['meditation','knowledge'],             'neutral'),
('Lucid Dreaming Practice',     'uncommon', ['meditation','observation'],           'neutral'),
('Yoga Nidra',                  'uncommon', ['meditation','endurance'],             'neutral'),
('Restorative Yoga',            'common',   ['meditation','endurance'],             'neutral'),
('Acupressure (Self)',          'uncommon', ['medicine','meditation'],              'neutral'),
# ── SCIENCE & LEARNING ───────────────────────────────────────
('Amateur Science Experiments', 'uncommon', ['chemistry','biology','observation'],  'neutral'),
('Citizen Science Participation','common',  ['observation','knowledge'],            'neutral'),
('History Study (Ancient)',     'uncommon', ['knowledge','history'],                'neutral'),
('History Study (Military)',    'uncommon', ['knowledge','history','tactics'],      'neutral'),
('History Study (WWII)',        'common',   ['knowledge','history'],                'neutral'),
('History Study (Cold War)',    'uncommon', ['knowledge','history'],                'neutral'),
('History Study (Medieval)',    'uncommon', ['knowledge','history'],                'neutral'),
('Philosophy Study',            'uncommon', ['knowledge','introspection'],          'neutral'),
('Ethics Study',                'uncommon', ['knowledge'],                          'good'),
('Economics Study (Hobby)',     'uncommon', ['knowledge','mathematics'],            'neutral'),
('Stock Market / Investing',    'uncommon', ['knowledge','mathematics'],            'neutral'),
('Cryptocurrency',              'uncommon', ['knowledge','mathematics'],            'neutral'),
('Psychology Study (Hobby)',    'uncommon', ['knowledge','perception'],             'neutral'),
('Law Study (Hobby)',           'uncommon', ['knowledge'],                          'neutral'),
('Geography Study',             'common',   ['knowledge','navigation'],             'neutral'),
('Political Science Study',     'uncommon', ['knowledge','social'],                 'neutral'),
('Theology Study',              'uncommon', ['knowledge','history'],                'neutral'),
('Anthropology Study',          'rare',     ['knowledge','history'],                'neutral'),
('Archaeology Study',           'rare',     ['knowledge','history'],                'neutral'),
('Genealogy / Family History',  'common',   ['knowledge','organization'],           'neutral'),
('Speed Reading',               'uncommon', ['reading','knowledge'],                'neutral'),
('Memory Training',             'uncommon', ['memory','knowledge'],                 'neutral'),
('Mental Arithmetic',           'uncommon', ['mathematics','memory'],               'neutral'),
('Chess Study (Opening Theory)','rare',     ['strategy','memory'],                  'neutral'),
# ── FILM, TV & MEDIA ─────────────────────────────────────────
('Filmmaking (Short Films)',    'uncommon', ['creativity','storytelling'],          'neutral'),
('Video Editing',               'common',   ['creativity','digital_art'],           'neutral'),
('Film Study / Cinephilia',     'uncommon', ['knowledge','observation'],            'neutral'),
('Anime Watching',              'common',   ['knowledge'],                          'neutral'),
('K-Drama Watching',            'common',   ['knowledge'],                          'neutral'),
('Documentary Watching',        'common',   ['knowledge','observation'],            'neutral'),
('Stand-Up Comedy (Performing)','rare',     ['public_speaking','humor'],            'neutral'),
('Improv Comedy',               'uncommon', ['acting','social'],                    'neutral'),
('Community Theatre Acting',    'uncommon', ['acting','social','public_speaking'],  'neutral'),
('Amateur Film Acting',         'uncommon', ['acting','social'],                    'neutral'),
('Voice Acting (Hobby)',        'uncommon', ['acting','public_speaking'],           'neutral'),
('Podcasting (Listener)',       'common',   ['knowledge'],                          'neutral'),
('Anime Cosplay',               'uncommon', ['sewing','creativity'],                'neutral'),
('Cosplay (General)',           'common',   ['sewing','creativity'],                'neutral'),
('Prop Making',                 'uncommon', ['carpentry','creativity'],             'neutral'),
# ── FASHION, BEAUTY & LIFESTYLE ──────────────────────────────
('Fashion Design (Hobby)',      'uncommon', ['sewing','creativity'],                'neutral'),
('Vintage Fashion',             'uncommon', ['fashion','knowledge'],                'neutral'),
('Thrift Shopping',             'common',   ['fashion','knowledge'],                'neutral'),
('Makeup Artistry (Hobby)',     'common',   ['creativity','precision'],             'neutral'),
('SFX Makeup',                  'rare',     ['creativity','chemistry'],             'neutral'),
('Nail Art',                    'common',   ['creativity','precision'],             'neutral'),
('Hair Styling / Cutting',      'common',   ['precision','social'],                 'neutral'),
('Jewellery Making',            'common',   ['precision','creativity'],             'neutral'),
('Beading',                     'common',   ['precision','patience'],               'neutral'),
('Skincare Routine (Hobby)',    'common',   ['chemistry','knowledge'],              'neutral'),
('Interior Design (Hobby)',     'common',   ['creativity','design'],                'neutral'),
# ── SOCIAL & CULTURAL ────────────────────────────────────────
('Volunteering (General)',      'common',   ['social','teamwork'],                  'good'),
('Community Service',           'common',   ['social','teamwork'],                  'good'),
('Historical Reenactment (Medieval)','rare',['history','acting','combat_training'],'neutral'),
('Historical Reenactment (WWII)','rare',   ['history','acting','firearms'],        'neutral'),
('Historical Reenactment (Roman)','very_rare',['history','acting'],                'neutral'),
('Civil War Reenactment',       'rare',     ['history','acting'],                   'neutral'),
('Viking Reenactment',          'rare',     ['history','acting','melee'],           'neutral'),
('Magic / Illusion (Hobby)',    'uncommon', ['sleight_of_hand','deception'],        'neutral'),
('Mentalism',                   'rare',     ['perception','deception','psychology'],'neutral'),
('Street Magic',                'rare',     ['sleight_of_hand','social'],           'neutral'),
('Ventriloquism',               'very_rare',['acting','coordination'],              'neutral'),
('Puppetry',                    'uncommon', ['acting','creativity'],                'neutral'),
('Storytelling (Oral)',         'common',   ['storytelling','public_speaking'],     'neutral'),
('Genealogy Research',          'common',   ['research','knowledge'],               'neutral'),
('Genealogy Travel',            'uncommon', ['research','navigation'],              'neutral'),
('Cultural Heritage Crafts',    'uncommon', ['crafting','history'],                 'neutral'),
('Board Game Design',           'rare',     ['game_design','creativity'],           'neutral'),
('Karaoke Hosting',             'uncommon', ['social','singing'],                   'neutral'),
# ── VEHICLES & TRANSPORT ─────────────────────────────────────
('Car Restoration',             'rare',     ['mechanics','knowledge','welding'],    'neutral'),
('Custom Car Building',         'very_rare',['mechanics','creativity','welding'],   'neutral'),
('Car Detailing',               'common',   ['mechanics','patience'],               'neutral'),
('Car Photography',             'uncommon', ['photography','knowledge'],            'neutral'),
('Drag Racing (Amateur)',       'rare',     ['driving','reflexes'],                 'neutral'),
('Rally Driving (Amateur)',     'very_rare',['driving','agility'],                  'neutral'),
('Off-Road Driving',            'uncommon', ['driving','agility'],                  'neutral'),
('Motorcycle Riding',           'common',   ['driving','coordination'],             'neutral'),
('Motorcycle Customizing',      'rare',     ['mechanics','creativity'],             'neutral'),
('Go-Kart Racing',              'common',   ['driving','reflexes'],                 'neutral'),
('RC Cars (Hobby)',             'common',   ['coordination','mechanics'],           'neutral'),
('RC Planes',                   'uncommon', ['coordination','electronics'],         'neutral'),
('RC Helicopters',              'rare',     ['coordination','electronics'],         'neutral'),
('Model Trains',                'uncommon', ['patience','precision'],               'neutral'),
('Model Ships',                 'uncommon', ['patience','precision'],               'neutral'),
('Model Aircraft',              'uncommon', ['patience','precision'],               'neutral'),
('Sailing (Dinghy)',            'uncommon', ['sailing','navigation'],               'neutral'),
('Powerboating',                'uncommon', ['boating','navigation'],               'neutral'),
('Jet Ski / PWC',               'uncommon', ['boating','agility'],                  'neutral'),
('Paragliding',                 'rare',     ['piloting','agility'],                 'neutral'),
('Hang Gliding',                'very_rare',['piloting','agility'],                 'neutral'),
('Microlight Flying',           'rare',     ['piloting','navigation'],              'neutral'),
('Hot Air Ballooning',          'very_rare',['piloting','endurance'],               'neutral'),
('Ultralight Aircraft',         'very_rare',['piloting','navigation'],              'neutral'),
# ── OUTDOOR & ADVENTURE ─────────────────────────────────────
('Urban Exploration (Urbex)',   'uncommon', ['climbing','navigation','stealth'],    'neutral'),
('Storm Chasing',               'very_rare',['observation','driving','meteorology'],'neutral'),
('Cave Diving',                 'legendary',['diving','navigation','endurance'],    'neutral'),
('Ice Climbing',                'rare',     ['climbing','endurance','agility'],     'neutral'),
('Speed Climbing',              'rare',     ['climbing','agility','endurance'],     'neutral'),
('Mountaineering',              'rare',     ['climbing','survival','navigation'],   'neutral'),
('Via Ferrata',                 'uncommon', ['climbing','agility'],                 'neutral'),
('Canyoning',                   'rare',     ['climbing','diving','navigation'],     'neutral'),
('Rappelling / Abseiling',      'uncommon', ['climbing','agility'],                 'neutral'),
('River Rafting',               'uncommon', ['boating','agility'],                  'neutral'),
('White Water Kayaking',        'rare',     ['boating','agility','endurance'],      'neutral'),
('Coasteering',                 'rare',     ['swimming','climbing','agility'],      'neutral'),
('Freediving',                  'very_rare',['diving','breath_control','endurance'],'neutral'),
('Spearfishing',                'rare',     ['diving','patience'],                  'neutral'),
('Night Diving',                'rare',     ['diving','endurance'],                 'neutral'),
('Dune Bashing (Sand Driving)', 'rare',     ['driving','agility'],                  'neutral'),
('Sandboarding',                'uncommon', ['agility','balance'],                  'neutral'),
('Zorbing',                     'uncommon', ['agility'],                            'neutral'),
('Geocaching',                  'common',   ['navigation','puzzle_solving'],        'neutral'),
('Letterboxing (Trail)',        'common',   ['navigation','puzzle_solving'],        'neutral'),
('Orienteering',                'uncommon', ['navigation','running'],               'neutral'),
('Night Hiking',                'uncommon', ['navigation','survival'],              'neutral'),
('Wild Camping',                'uncommon', ['survival','navigation'],              'neutral'),
('Hammock Camping',             'common',   ['survival','navigation'],              'neutral'),
('Bushcraft',                   'uncommon', ['survival','fire_making','crafting'],  'neutral'),
('Fire Starting (Primitive)',   'uncommon', ['fire_making','survival'],             'neutral'),
('Primitive Skills',            'rare',     ['survival','crafting','fire_making'],  'neutral'),
('Snow Camping',                'rare',     ['survival','endurance'],               'neutral'),
('Desert Survival',             'rare',     ['survival','navigation'],              'neutral'),
('Caving / Spelunking',         'uncommon', ['climbing','navigation'],              'neutral'),
('Long Distance Hiking (Thru)', 'rare',     ['endurance','navigation','survival'],  'neutral'),
('Packrafting',                 'rare',     ['boating','survival','navigation'],    'neutral'),
# ── PERFORMANCE & CIRCUS ────────────────────────────────────
('Juggling',                    'uncommon', ['coordination','agility'],             'neutral'),
('Juggling (5+ objects)',       'rare',     ['coordination','agility','patience'],  'neutral'),
('Devil Sticks',                'uncommon', ['coordination'],                       'neutral'),
('Diabolos',                    'uncommon', ['coordination','agility'],             'neutral'),
('Unicycling',                  'uncommon', ['balance','coordination'],             'neutral'),
('Unicycling (Advanced)',       'rare',     ['balance','agility'],                  'neutral'),
('Slacklining',                 'uncommon', ['balance','agility'],                  'neutral'),
('Highlining',                  'very_rare',['balance','agility','endurance'],      'neutral'),
('Acrobatics (Hobby)',          'uncommon', ['acrobatics','agility'],               'neutral'),
('Tumbling',                    'uncommon', ['acrobatics','agility'],               'neutral'),
('Hand Balancing',              'rare',     ['balance','strength'],                 'neutral'),
('Contortion',                  'very_rare',['agility','flexibility'],              'neutral'),
('Stilt Walking',               'uncommon', ['balance','coordination'],             'neutral'),
('Tightrope Walking',           'rare',     ['balance','agility'],                  'neutral'),
('Mime',                        'uncommon', ['acting','coordination'],              'neutral'),
('Physical Comedy',             'uncommon', ['acting','agility'],                   'neutral'),
# ── MISC & UNIQUE ────────────────────────────────────────────
('Competitive Eating',          'rare',     ['endurance','stomach_of_steel'],       'neutral'),
('Hot Dog Eating Contest',      'rare',     ['endurance'],                          'neutral'),
('Competitive Punning',         'legendary',['humor','vocabulary'],                 'neutral'),
('Competitive Spelling',        'rare',     ['vocabulary','memory'],                'neutral'),
('Math Olympiad (Hobby Prep)',  'rare',     ['mathematics','memory'],               'neutral'),
('Dumpster Diving (Freeganism)','uncommon', ['survival','endurance'],               'neutral'),
('Extreme Couponing',           'uncommon', ['organization','mathematics'],         'neutral'),
('ASMR Content Creation',       'common',   ['patience','creativity'],              'neutral'),
('True Crime Study',            'common',   ['knowledge','perception'],             'neutral'),
('Conspiracy Theory Research',  'uncommon', ['knowledge','paranoia'],               'neutral'),
('Ghost Hunting',               'uncommon', ['observation','perception'],           'neutral'),
('Paranormal Investigation',    'rare',     ['observation','knowledge'],            'neutral'),
('Cryptozoology Study',         'rare',     ['knowledge','observation'],            'neutral'),
('UFO Spotting / UAP Study',    'uncommon', ['observation','astronomy'],            'neutral'),
('Escape Room Design',          'rare',     ['puzzle_solving','creativity'],        'neutral'),
('Party Planning',              'common',   ['organization','social'],              'neutral'),
('Flower Arranging',            'common',   ['botany','creativity'],                'neutral'),
('Ikebana (Japanese Flowers)',  'rare',     ['botany','creativity','patience'],     'neutral'),
('Terrarium Design',            'common',   ['gardening','creativity'],             'neutral'),
('Fairy Garden Design',         'uncommon', ['gardening','creativity'],             'neutral'),
('Jigsaw Puzzles',              'common',   ['patience','spatial_reasoning'],       'neutral'),
('3D Puzzles',                  'uncommon', ['spatial_reasoning','patience'],       'neutral'),
('Mechanical Puzzles',          'uncommon', ['problem_solving','patience'],         'neutral'),
('Word Games',                  'common',   ['vocabulary','memory'],                'neutral'),
('Sudoku',                      'common',   ['mathematics','logic'],                'neutral'),
('Crossword Puzzles',           'common',   ['vocabulary','knowledge'],             'neutral'),
('Cryptic Crosswords',          'rare',     ['vocabulary','logic'],                 'neutral'),
('Logic Puzzles',               'uncommon', ['logic','mathematics'],                'neutral'),
('Watching Sports (General)',   'common',   ['knowledge','social'],                 'neutral'),
('Watching Football (Fan)',     'common',   ['knowledge','social'],                 'neutral'),
('Watching MMA / UFC',          'common',   ['knowledge','social'],                 'neutral'),
('Fantasy Sports Leagues',      'common',   ['knowledge','mathematics'],            'neutral'),
('Sports Statistics Analysis',  'uncommon', ['mathematics','knowledge'],            'neutral'),
('Attending Live Concerts',     'common',   ['social','music'],                     'neutral'),
('Music Festival Attendance',   'common',   ['social','endurance'],                 'neutral'),
('Convention Attendance',       'common',   ['social','knowledge'],                 'neutral'),
('Travel (International)',      'common',   ['navigation','languages'],             'neutral'),
('Backpacking (Budget Travel)', 'common',   ['survival','navigation'],              'neutral'),
('Solo Travel',                 'uncommon', ['navigation','self_reliance'],         'neutral'),
('Extreme Travel',              'rare',     ['survival','navigation','endurance'],  'neutral'),
('Train Travel (Scenic)',       'common',   ['navigation','knowledge'],             'neutral'),
('Cruise Travel',               'uncommon', ['social','navigation'],                'neutral'),
('Volunteering Abroad',         'rare',     ['social','languages'],                 'good'),
('Competitive Trivia',          'uncommon', ['knowledge','memory'],                 'neutral'),
('Pub Quiz',                    'common',   ['knowledge','social'],                 'neutral'),
('Treasure Hunting',            'uncommon', ['navigation','knowledge'],             'neutral'),
('Metal Detecting',             'uncommon', ['navigation','knowledge','patience'],  'neutral'),
('Coin Rolling / Searching',    'uncommon', ['patience','knowledge'],               'neutral'),
('Dumpster Diving for Finds',   'uncommon', ['knowledge','survival'],               'neutral'),
('Garage Sale / Thrift Hunting','common',  ['knowledge','negotiation'],            'neutral'),
('Refurbishing Electronics',    'uncommon', ['electronics','patience'],             'neutral'),
('Upcycling Furniture',         'common',   ['carpentry','creativity'],             'neutral'),
('Charity Fundraising',         'uncommon', ['social','public_speaking'],           'good'),
('Amateur Geology Field Work',  'uncommon', ['geology','survival'],                 'neutral'),
('Stone Skipping (Competitive)','uncommon', ['coordination','patience'],            'neutral'),
('Whittling (Casual)',          'common',   ['patience','precision'],               'neutral'),
('Chain-Saw Carving',           'rare',     ['carpentry','endurance'],              'neutral'),
('Ice Sculpting',               'very_rare',['sculpting','endurance'],              'neutral'),
('Sand Art / Sand Sculpture',   'uncommon', ['sculpting','creativity'],             'neutral'),
('Snow Sculpture',              'uncommon', ['sculpting','endurance'],              'neutral'),
('Flash Mob Participation',     'uncommon', ['dancing','social'],                   'neutral'),
('Busking (Street Performance)','uncommon', ['music','social'],                     'neutral'),
('Stand-Up Paddleboarding',     'common',   ['balance','endurance'],                'neutral'),
('Outrigger Canoe',             'uncommon', ['rowing','endurance'],                 'neutral'),
('Dragon Boat Racing',          'uncommon', ['rowing','teamwork'],                  'neutral'),
('Aqua Aerobics',               'common',   ['swimming','endurance'],               'neutral'),
('Open Water Swimming',         'uncommon', ['swimming','endurance'],               'neutral'),
('Ice Swimming',                'rare',     ['swimming','endurance'],               'neutral'),
]

# ── Merge with deduplication ─────────────────────────────────
existing_labels = {h['label'].lower() for h in d['hobbies']}
next_id = max(int(h['id'].split('-')[1]) for h in d['hobbies']) + 1
added = 0
for label, rarity, skills, alignment in RAW:
    if label.lower() in existing_labels:
        continue
    d['hobbies'].append({
        'id':        f'hobby-{next_id:05d}',
        'label':     label,
        'rarity':    rarity,
        'skills':    skills,
        'alignment': alignment,
    })
    existing_labels.add(label.lower())
    next_id += 1
    added += 1

with open(PATH, 'w', encoding='utf-8', newline='\n') as f:
    json.dump(d, f, ensure_ascii=False, indent=2)

print(f'Hobbies: +{added} new  →  total {len(d["hobbies"])}')
print(f'Occupations: {len(d["occupations"])} (dup fixed)')
